## Preprocesamiento de datos

#### En esta fase se realizará la limpieza y preparación del conjunto de datos para garantizar su calidad antes del análisis. Se revisarán los valores nulos, los tipos de datos y aquellas variables que puedan afectar al análisis o al posterior desarrollo del dashboard en Power BI.

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

#### Cargamos de nuevo el dataset original para trabajar siempre desde los datos en bruto y aplicar las transformaciones de limpieza en este notebook.

In [2]:
df = pd.read_csv("../data/raw/resortworldwide.csv")
df.head(2)

,URL,Rate,NameResort,Stars,Km Freeride,Continent,Country,State/Province,Altitude,Easy,Intermediate,Difficult,Adult,Currency,Ski resort size,"Slope offering, variety of runs",Lifts and cable cars,Snow reliability,"Access, on-site parking","Orientation (trail map, information boards, sign-postings)",Cleanliness and hygiene,Environmentally friendly ski operation,"Mountain restaurants, ski huts, gastronomy",Après-ski,Accommodation offering directly at the slopes and lifts,Families and children,Beginners,Snow parks,Cross-country skiing and trails,country,latitude,longitude,Total Kms
0,http://www.skiresort.info/ski-resort/kitzski-k...,4.9,KitzSki – Kitzbühel/Kirchberg,5.0,45.0,Europe,Austria,Tyrol (Tirol),2000.0,101.0,61.0,17.0,55,European Euro,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","4,0","5,0","5,0","5,0","5,0","5,0",AT,47.516231,14.550072,179
1,http://www.skiresort.info/ski-resort/ischglsam...,4.8,Ischgl/Samnaun – Silvretta Arena,5.0,15.0,Europe,Austria,Tyrol (Tirol),2872.0,47.0,142.0,49.0,53,European Euro,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","5,0","5,0","4,0","4,0","5,0","4,0",AT,47.516231,14.550072,238

In [3]:
df.shape

(5478, 33)

## Valores Nulos

#### Antes de aplicar cualquier transformación, analizamos la cantidad y el porcentaje de valores nulos de cada variable. Esta información nos permitirá decidir qué columnas conservar, tratar o eliminar durante el proceso de limpieza.

In [4]:
nulls = pd.DataFrame({
    "Nulos": df.isnull().sum(),
    "Porcentaje (%)": round(df.isnull().mean() * 100, 2)
}).sort_values(by="Porcentaje (%)", ascending=False)

nulls

                                                    Nulos  Porcentaje (%)
Stars                                                5065           92.46
Accommodation offering directly at the slopes a...   5049           92.17
Après-ski                                            5049           92.17
Mountain restaurants, ski huts, gastronomy           5049           92.17
Environmentally friendly ski operation               5049           92.17
Cross-country skiing and trails                      5049           92.17
Snow parks                                           5049           92.17
Beginners                                            5049           92.17
Families and children                                5049           92.17
Cleanliness and hygiene                              5049           92.17
Orientation (trail map, information boards, sig...   5049           92.17
Access, on-site parking                              5049           92.17
Snow reliability                                     5049           92.17
Km Freeride                                          4998           91.24
Ski resort size                                      2026           36.98
Lifts and cable cars                                 2026           36.98
Slope offering, variety of runs                      2026           36.98
Rate                                                 2007           36.64
country                                               599           10.93
longitude                                             598           10.92
latitude                                              598           10.92
Adult                                                   9            0.16
State/Province                                          9            0.16
Continent                                               9            0.16
Currency                                                9            0.16
Altitude                                                9            0.16
Country                                                 9            0.16
URL                                                     0            0.00
NameResort                                              0            0.00
Intermediate                                            0            0.00
Easy                                                    0            0.00
Difficult                                               0            0.00
Total Kms                                               0            0.00

In [5]:
nulls[nulls["Nulos"] > 0]

                                                    Nulos  Porcentaje (%)
Stars                                                5065           92.46
Accommodation offering directly at the slopes a...   5049           92.17
Après-ski                                            5049           92.17
Mountain restaurants, ski huts, gastronomy           5049           92.17
Environmentally friendly ski operation               5049           92.17
Cross-country skiing and trails                      5049           92.17
Snow parks                                           5049           92.17
Beginners                                            5049           92.17
Families and children                                5049           92.17
Cleanliness and hygiene                              5049           92.17
Orientation (trail map, information boards, sig...   5049           92.17
Access, on-site parking                              5049           92.17
Snow reliability                                     5049           92.17
Km Freeride                                          4998           91.24
Ski resort size                                      2026           36.98
Lifts and cable cars                                 2026           36.98
Slope offering, variety of runs                      2026           36.98
Rate                                                 2007           36.64
country                                               599           10.93
longitude                                             598           10.92
latitude                                              598           10.92
Adult                                                   9            0.16
State/Province                                          9            0.16
Continent                                               9            0.16
Currency                                                9            0.16
Altitude                                                9            0.16
Country                                                 9            0.16

In [6]:
columnas_revision = [
    "Stars",
    "Rate",
    "Ski resort size",
    "Slope offering, variety of runs",
    "Lifts and cable cars",
    "Snow reliability",
    "Access, on-site parking",
    "Orientation (trail map, information boards, sign-postings)",
    "Cleanliness and hygiene",
    "Environmentally friendly ski operation",
    "Mountain restaurants, ski huts, gastronomy",
    "Après-ski",
    "Accommodation offering directly at the slopes and lifts",
    "Beginners",
    "Snow parks",
    "Cross-country skiing and trails",
    "Families and children",
    "Km Freeride"
]

#### Se eliminan los espacios en blanco al inicio y al final de los nombres de las columnas para evitar errores durante el tratamiento y análisis del dataset.

In [7]:
df.columns = df.columns.str.strip()

In [8]:
df[columnas_revision].head(10)

,Stars,Rate,Ski resort size,"Slope offering, variety of runs",Lifts and cable cars,Snow reliability,"Access, on-site parking","Orientation (trail map, information boards, sign-postings)",Cleanliness and hygiene,Environmentally friendly ski operation,"Mountain restaurants, ski huts, gastronomy",Après-ski,Accommodation offering directly at the slopes and lifts,Beginners,Snow parks,Cross-country skiing and trails,Families and children,Km Freeride
0,5.0,4.9,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","4,0","5,0","5,0","5,0","5,0","5,0",45.0
1,5.0,4.8,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","5,0","5,0","4,0","5,0","4,0","4,0",15.0
2,5.0,4.8,"5,0",5.0,"5,0",4.0,"5,0","4,0","5,0","5,0","5,0","4,0","4,0","5,0","5,0","5,0","5,0",26.0
3,5.0,4.8,"5,0",5.0,"5,0",5.0,"4,0","4,0","4,0","4,0","5,0","5,0","5,0","5,0","4,0","4,0","5,0",200.0
4,5.0,4.8,"5,0",5.0,"5,0",5.0,"4,0","5,0","4,0","4,0","5,0","4,0","4,0","4,0","5,0","4,0","5,0",28.0
5,5.0,4.7,"5,0",5.0,"5,0",4.0,"3,0","5,0","5,0","4,0","5,0","5,0","5,0","5,0","5,0","4,0","5,0",0.0
6,5.0,4.7,"4,0",5.0,"5,0",5.0,"5,0","5,0","5,0","4,0","5,0","4,0","5,0","5,0","4,0","3,0","5,0",3.6
7,5.0,4.7,"5,0",5.0,"5,0",5.0,"4,0","4,0","5,0","4,0","5,0","4,0","5,0","4,0","5,0","4,0","5,0",3.0
8,4.0,4.7,"5,0",5.0,"5,0",5.0,"4,0","4,0","5,0","4,0","5,0","5,0","5,0","3,0","5,0","4,0","5,0",4.0
9,5.0,4.7,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","5,0","5,0","4,0","4,0","3,0","4,0",0.0

In [9]:
df.columns.tolist()

['URL',
 'Rate',
 'NameResort',
 'Stars',
 'Km Freeride',
 'Continent',
 'Country',
 'State/Province',
 'Altitude',
 'Easy',
 'Intermediate',
 'Difficult',
 'Adult',
 'Currency',
 'Ski resort size',
 'Slope offering, variety of runs',
 'Lifts and cable cars',
 'Snow reliability',
 'Access, on-site parking',
 'Orientation (trail map, information boards, sign-postings)',
 'Cleanliness and hygiene',
 'Environmentally friendly ski operation',
 'Mountain restaurants, ski huts, gastronomy',
 'Après-ski',
 'Accommodation offering directly at the slopes and lifts',
 'Families and children',
 'Beginners',
 'Snow parks',
 'Cross-country skiing and trails',
 'country',
 'latitude',
 'longitude',
 'Total Kms']

In [10]:
for col in df.columns:
    print(repr(col))

'URL'
'Rate'
'NameResort'
'Stars'
'Km Freeride'
'Continent'
'Country'
'State/Province'
'Altitude'
'Easy'
'Intermediate'
'Difficult'
'Adult'
'Currency'
'Ski resort size'
'Slope offering, variety of runs'
'Lifts and cable cars'
'Snow reliability'
'Access, on-site parking'
'Orientation (trail map, information boards, sign-postings)'
'Cleanliness and hygiene'
'Environmentally friendly ski operation'
'Mountain restaurants, ski huts, gastronomy'
'Après-ski'
'Accommodation offering directly at the slopes and lifts'
'Families and children'
'Beginners'
'Snow parks'
'Cross-country skiing and trails'
'country'
'latitude'
'longitude'
'Total Kms'

In [11]:
for col in df.columns:
    print(repr(col))

'URL'
'Rate'
'NameResort'
'Stars'
'Km Freeride'
'Continent'
'Country'
'State/Province'
'Altitude'
'Easy'
'Intermediate'
'Difficult'
'Adult'
'Currency'
'Ski resort size'
'Slope offering, variety of runs'
'Lifts and cable cars'
'Snow reliability'
'Access, on-site parking'
'Orientation (trail map, information boards, sign-postings)'
'Cleanliness and hygiene'
'Environmentally friendly ski operation'
'Mountain restaurants, ski huts, gastronomy'
'Après-ski'
'Accommodation offering directly at the slopes and lifts'
'Families and children'
'Beginners'
'Snow parks'
'Cross-country skiing and trails'
'country'
'latitude'
'longitude'
'Total Kms'

In [12]:
df[columnas_revision].head(10)

,Stars,Rate,Ski resort size,"Slope offering, variety of runs",Lifts and cable cars,Snow reliability,"Access, on-site parking","Orientation (trail map, information boards, sign-postings)",Cleanliness and hygiene,Environmentally friendly ski operation,"Mountain restaurants, ski huts, gastronomy",Après-ski,Accommodation offering directly at the slopes and lifts,Beginners,Snow parks,Cross-country skiing and trails,Families and children,Km Freeride
0,5.0,4.9,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","4,0","5,0","5,0","5,0","5,0","5,0",45.0
1,5.0,4.8,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","5,0","5,0","4,0","5,0","4,0","4,0",15.0
2,5.0,4.8,"5,0",5.0,"5,0",4.0,"5,0","4,0","5,0","5,0","5,0","4,0","4,0","5,0","5,0","5,0","5,0",26.0
3,5.0,4.8,"5,0",5.0,"5,0",5.0,"4,0","4,0","4,0","4,0","5,0","5,0","5,0","5,0","4,0","4,0","5,0",200.0
4,5.0,4.8,"5,0",5.0,"5,0",5.0,"4,0","5,0","4,0","4,0","5,0","4,0","4,0","4,0","5,0","4,0","5,0",28.0
5,5.0,4.7,"5,0",5.0,"5,0",4.0,"3,0","5,0","5,0","4,0","5,0","5,0","5,0","5,0","5,0","4,0","5,0",0.0
6,5.0,4.7,"4,0",5.0,"5,0",5.0,"5,0","5,0","5,0","4,0","5,0","4,0","5,0","5,0","4,0","3,0","5,0",3.6
7,5.0,4.7,"5,0",5.0,"5,0",5.0,"4,0","4,0","5,0","4,0","5,0","4,0","5,0","4,0","5,0","4,0","5,0",3.0
8,4.0,4.7,"5,0",5.0,"5,0",5.0,"4,0","4,0","5,0","4,0","5,0","5,0","5,0","3,0","5,0","4,0","5,0",4.0
9,5.0,4.7,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","5,0","5,0","4,0","4,0","3,0","4,0",0.0

In [13]:
df[df["Snow parks"].isna()].head()

,URL,Rate,NameResort,Stars,Km Freeride,Continent,Country,State/Province,Altitude,Easy,Intermediate,Difficult,Adult,Currency,Ski resort size,"Slope offering, variety of runs",Lifts and cable cars,Snow reliability,"Access, on-site parking","Orientation (trail map, information boards, sign-postings)",Cleanliness and hygiene,Environmentally friendly ski operation,"Mountain restaurants, ski huts, gastronomy",Après-ski,Accommodation offering directly at the slopes and lifts,Families and children,Beginners,Snow parks,Cross-country skiing and trails,country,latitude,longitude,Total Kms
59,http://www.skiresort.info/ski-resort/filzmoos/,3.7,. Filzmoos,2.0,0.0,Europe,Austria,Salzburg (Salzburger Land),1645.0,6.0,6.0,1.0,43,European Euro,"2,3",2.5,"3,4",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AT,47.516231,14.550072,13
75,http://www.skiresort.info/ski-resort/hochficht/,3.6,. Hochficht,2.0,3.0,Europe,Austria,Upper Austria (Oberosterreich),1338.0,9.0,10.0,1.0,39,European Euro,"2,4",2.6,"3,5",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AT,47.516231,14.550072,20
76,http://www.skiresort.info/ski-resort/patscherk...,3.6,. Patscherkofel – Innsbruck-Igls,3.0,0.0,Europe,Austria,Tyrol (Tirol),1969.0,5.0,9.0,4.0,37,European Euro,"2,4",2.7,"4,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AT,47.516231,14.550072,18
77,http://www.skiresort.info/ski-resort/moenichki...,3.6,. Mönichkirchen/Mariensee,2.0,0.0,Europe,Austria,Lower Austria (Niederosterreich),1450.0,5.5,6.0,2.0,"35,50",European Euro,"2,3",2.6,"3,9",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AT,47.516231,14.550072,13
78,http://www.skiresort.info/ski-resort/sportgast...,3.6,Sportgastein,5.0,7.7,Europe,Austria,Salzburg (Salzburger Land),2686.0,3.5,13.2,1.5,52,European Euro,"2,5",2.7,"4,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AT,47.516231,14.550072,18

In [14]:
df[df["Snow parks"].notna()].head()

,URL,Rate,NameResort,Stars,Km Freeride,Continent,Country,State/Province,Altitude,Easy,Intermediate,Difficult,Adult,Currency,Ski resort size,"Slope offering, variety of runs",Lifts and cable cars,Snow reliability,"Access, on-site parking","Orientation (trail map, information boards, sign-postings)",Cleanliness and hygiene,Environmentally friendly ski operation,"Mountain restaurants, ski huts, gastronomy",Après-ski,Accommodation offering directly at the slopes and lifts,Families and children,Beginners,Snow parks,Cross-country skiing and trails,country,latitude,longitude,Total Kms
0,http://www.skiresort.info/ski-resort/kitzski-k...,4.9,KitzSki – Kitzbühel/Kirchberg,5.0,45.0,Europe,Austria,Tyrol (Tirol),2000.0,101.0,61.0,17.0,55,European Euro,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","4,0","5,0","5,0","5,0","5,0","5,0",AT,47.516231,14.550072,179
1,http://www.skiresort.info/ski-resort/ischglsam...,4.8,Ischgl/Samnaun – Silvretta Arena,5.0,15.0,Europe,Austria,Tyrol (Tirol),2872.0,47.0,142.0,49.0,53,European Euro,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","5,0","5,0","4,0","4,0","5,0","4,0",AT,47.516231,14.550072,238
2,http://www.skiresort.info/ski-resort/skiwelt-w...,4.8,SkiWelt Wilder Kaiser-Brixental,5.0,26.0,Europe,Austria,Tyrol (Tirol),1957.0,122.0,129.0,33.0,49,European Euro,"5,0",5.0,"5,0",4.0,"5,0","4,0","5,0","5,0","5,0","4,0","4,0","5,0","5,0","5,0","5,0",AT,47.516231,14.550072,284
3,http://www.skiresort.info/ski-resort/st-antons...,4.8,Ski Arlberg,5.0,200.0,Europe,Austria,Tyrol (Tirol),2811.0,132.0,123.0,50.0,53,European Euro,"5,0",5.0,"5,0",5.0,"4,0","4,0","4,0","4,0","5,0","5,0","5,0","5,0","5,0","4,0","4,0",AT,47.516231,14.550072,305
4,http://www.skiresort.info/ski-resort/serfaus-f...,4.8,Serfaus-Fiss-Ladis,5.0,28.0,Europe,Austria,Tyrol (Tirol),2820.0,47.0,123.0,28.0,51,European Euro,"5,0",5.0,"5,0",5.0,"4,0","5,0","4,0","4,0","5,0","4,0","4,0","5,0","4,0","5,0","4,0",AT,47.516231,14.550072,198

#### Antes de transformar las variables, comprobamos el tipo de dato para identificar aquellas que han sido importadas como texto y necesitan convertirse a formato numérico.

In [15]:
df[columnas_revision].dtypes

Stars                                                         float64
Rate                                                          float64
Ski resort size                                                   str
Slope offering, variety of runs                               float64
Lifts and cable cars                                              str
Snow reliability                                              float64
Access, on-site parking                                           str
Orientation (trail map, information boards, sign-postings)        str
Cleanliness and hygiene                                           str
Environmentally friendly ski operation                            str
Mountain restaurants, ski huts, gastronomy                        str
Après-ski                                                         str
Accommodation offering directly at the slopes and lifts           str
Beginners                                                         str
Snow parks                                                        str
Cross-country skiing and trails                                   str
Families and children                                             str
Km Freeride                                                   float64
dtype: object

In [16]:
df["Après-ski"].value_counts(dropna=False)

Après-ski
NaN    5049
3,0     174
2,0     106
4,0      75
1,0      64
5,0      10
Name: count, dtype: int64

In [17]:
df["Families and children"].value_counts(dropna=False)

Families and children
NaN    5049
4,0     179
3,0     112
5,0     108
2,0      27
1,0       3
Name: count, dtype: int64

#### Las variables de valoración se convierten a formato numérico sustituyendo la coma decimal por un punto. Esto permitirá utilizarlas posteriormente en cálculos y visualizaciones.

In [18]:
columnas_valoracion = [
    "Ski resort size",
    "Lifts and cable cars",
    "Access, on-site parking",
    "Orientation (trail map, information boards, sign-postings)",
    "Cleanliness and hygiene",
    "Environmentally friendly ski operation",
    "Mountain restaurants, ski huts, gastronomy",
    "Après-ski",
    "Accommodation offering directly at the slopes and lifts",
    "Beginners",
    "Snow parks",
    "Cross-country skiing and trails",
    "Families and children"
]

In [19]:
for columna in columnas_valoracion:
    df[columna] = (
        df[columna]
        .str.replace(",", ".", regex=False)
        .astype(float)
    )

In [20]:
df[columnas_valoracion].dtypes

Ski resort size                                               float64
Lifts and cable cars                                          float64
Access, on-site parking                                       float64
Orientation (trail map, information boards, sign-postings)    float64
Cleanliness and hygiene                                       float64
Environmentally friendly ski operation                        float64
Mountain restaurants, ski huts, gastronomy                    float64
Après-ski                                                     float64
Accommodation offering directly at the slopes and lifts       float64
Beginners                                                     float64
Snow parks                                                    float64
Cross-country skiing and trails                               float64
Families and children                                         float64
dtype: object

#### ¿Las columnas con un 92 % de nulos corresponden siempre a las mismas estaciones?

In [21]:
df[df["Après-ski"].notna()].shape

(429, 33)

In [22]:
df[df["Families and children"].notna()].shape

(429, 33)

In [23]:
df[df["Snow reliability"].notna()].shape

(429, 33)

In [24]:
df[
    [
        "NameResort",
        "Country",
        "Rate",
        "Après-ski",
        "Families and children",
        "Snow reliability"
    ]
].dropna().head(390)

,NameResort,Country,Rate,Après-ski,Families and children,Snow reliability
0,KitzSki – Kitzbühel/Kirchberg,Austria,4.9,4.0,5.0,5.0
1,Ischgl/Samnaun – Silvretta Arena,Austria,4.8,5.0,4.0,5.0
2,SkiWelt Wilder Kaiser-Brixental,Austria,4.8,4.0,5.0,4.0
3,Ski Arlberg,Austria,4.8,5.0,5.0,5.0
4,Serfaus-Fiss-Ladis,Austria,4.8,4.0,5.0,5.0
...,...,...,...,...,...,...
3585,bolton-valley,USA,3.0,2.0,3.0,4.0
3596,breckenridge,USA,4.0,4.0,5.0,5.0
3611,buttermilk-mountain,USA,3.0,2.0,4.0,4.0
3702,heavenly,USA,4.0,4.0,4.0,5.0
3736,keystone,USA,4.0,4.0,5.0,5.0

#### Analizamos las filas con valor nulo en la columna de país para tomar una decisión adecuada.

In [25]:
df[df["Country"].isna()]

,URL,Rate,NameResort,Stars,Km Freeride,Continent,Country,State/Province,Altitude,Easy,Intermediate,Difficult,Adult,Currency,Ski resort size,"Slope offering, variety of runs",Lifts and cable cars,Snow reliability,"Access, on-site parking","Orientation (trail map, information boards, sign-postings)",Cleanliness and hygiene,Environmentally friendly ski operation,"Mountain restaurants, ski huts, gastronomy",Après-ski,Accommodation offering directly at the slopes and lifts,Families and children,Beginners,Snow parks,Cross-country skiing and trails,country,latitude,longitude,Total Kms
1830,http://www.skiresort.info/ski-resort/wildhaus-...,3.9,. Wildhaus – Gamserrugg (Toggenburg),3.0,12.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1831,http://www.skiresort.info/ski-resort/ehrwalder...,3.5,. Ehrwalder Wettersteinbahnen – Ehrwald,2.0,1.5,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1832,http://www.skiresort.info/ski-resort/ravna-pla...,3.0,. Ravna Planina,2.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1833,http://www.skiresort.info/ski-resort/savin-kuk...,2.9,. Savin Kuk – Žabljak,3.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1834,http://www.skiresort.info/ski-resort/snowworld...,2.7,. SnowWorld Rucphen (indoor ski area),1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1835,http://www.skiresort.info/ski-resort/raudalen/,NaN,. Raudalen,3.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1836,http://www.skiresort.info/ski-resort/snowworld...,NaN,. SnowWorld Terneuzen (indoor ski area),1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1837,http://www.skiresort.info/ski-resort/snowworld...,NaN,. SnowWorld Amsterdam (indoor ski area),1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1838,http://www.skiresort.info/ski-resort/roelzhang...,NaN,. Rölzhang – Wildenthal,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [26]:
df[df["Total Kms"] == 0].shape

(2117, 33)

In [27]:
df[df["Total Kms"] == 0][
    ["NameResort", "Country", "Total Kms", "Easy", "Intermediate", "Difficult"]
].head(300)

,NameResort,Country,Total Kms,Easy,Intermediate,Difficult
140,. Burglift – Stans,Austria,0,0.5,0.0,0.0
143,. Hohe Wand Wiese – Vienna (High Hills),Austria,0,0.1,0.4,0.0
145,. Alfaierlift – Gschnitz,Austria,0,0.3,0.2,0.0
147,. Kramsach,Austria,0,0.4,0.0,0.0
155,annerlbauerlifte-krieglach,Austria,0,0.5,0.0,0.0
...,...,...,...,...,...,...
1382,talma,Finland,0,0.5,0.3,0.0
1384,tornimaeki-mikkeli,Finland,0,0.0,0.0,0.0
1388,vatuski,Finland,0,0.0,0.0,0.0
1389,vierumaeki,Finland,0,0.0,0.0,0.0
1392,vuorenmaa,Finland,0,0.0,0.0,0.0

#### Aquí se ve que hay muchas estaciones con 0 km esquiables

In [28]:
df[df["Total Kms"] == 0]["Easy"].value_counts(dropna=False)

Easy
0.0    935
0.3    260
0.2    215
0.5    209
0.4    179
0.1    117
0.6     79
0.8     58
0.7     46
0.9     19
Name: count, dtype: int64

In [29]:
df[df["Total Kms"] == 0]["Intermediate"].value_counts(dropna=False)

Intermediate
0.0    1876
0.2      66
0.3      51
0.1      42
0.4      35
0.5      24
0.6      10
0.8       6
0.7       5
0.9       2
Name: count, dtype: int64

In [30]:
df[df["Total Kms"] == 0]["Difficult"].value_counts(dropna=False)

Difficult
0.0    2085
0.1      17
0.2       9
0.3       4
0.4       2
Name: count, dtype: int64

In [31]:
df[df["Total Kms"] > 0].shape

(3361, 33)

#### Comprobamos la consistencia de la variable `Total Kms` comparándola con la suma de los kilómetros de pistas fáciles, intermedias y difíciles.

In [32]:
df["Total Kms Calculados"] = (
    df["Easy"] +
    df["Intermediate"] +
    df["Difficult"]
)

In [33]:
(
    df["Total Kms"] != df["Total Kms Calculados"]
).sum()

np.int64(2458)

In [34]:
df[
    ["Easy", "Intermediate", "Difficult", "Total Kms", "Total Kms Calculados"]
].head(20)

     Easy  Intermediate  Difficult  Total Kms  Total Kms Calculados
0   101.0          61.0       17.0        179                 179.0
1    47.0         142.0       49.0        238                 238.0
2   122.0         129.0       33.0        284                 284.0
3   132.0         123.0       50.0        305                 305.0
4    47.0         123.0       28.0        198                 198.0
5   140.0         112.0       18.0        270                 270.0
6    28.7          41.3       13.0         83                  83.0
7    43.0          89.0       11.0        143                 143.0
8    46.4          68.3        8.3        122                 123.0
9    70.2          44.6       29.4        144                 144.2
10   60.0          45.0        8.0        113                 113.0
11   40.0          63.0       33.0        136                 136.0
12   61.0          35.0        4.0        100                 100.0
13   35.0          55.0       20.0        110                 110.0
14   52.0          41.0       19.0        112                 112.0
15   30.0          81.0        4.0        115                 115.0
16   30.0          28.0       19.0         77                  77.0
17   29.0          25.0       10.0         64                  64.0
18   13.0          25.0        3.0         41                  41.0
19   30.6          52.8        2.6         86                  86.0

In [35]:
df[
    df["Total Kms"] != df["Total Kms Calculados"]
][
    ["NameResort", "Easy", "Intermediate", "Difficult", "Total Kms", "Total Kms Calculados"]
].head(20)

,NameResort,Easy,Intermediate,Difficult,Total Kms,Total Kms Calculados
8,Schladming – Planai/​Hochwurzen/​Hauser Kaibl...,46.4,68.3,8.3,122,123.0
9,Sölden,70.2,44.6,29.4,144,144.2
22,Ski Juwel Alpbachtal Wildschönau,25.9,53.7,13.5,93,93.1
23,Damüls Mellau,29.7,48.0,1.7,79,79.4
30,Großarltal/Dorfgastein,25.5,43.1,1.5,70,70.1
33,Lermoos – Grubigstein,12.8,12.6,1.9,27,27.3
34,Golm,13.0,12.0,1.5,26,26.5
42,. Sillian – Thurntaler (Hochpustertal),5.6,15.0,1.1,21,21.7
44,. Spieljoch – Fügen,3.6,14.8,2.7,21,21.1
50,. Pitztal Glacier (Pitztaler Gletscher),3.8,16.2,0.7,20,20.7
54,. Ehrwalder Alm – Ehrwald,18.1,7.4,2.0,27,27.5
58,Kaunertal Glacier (Kaunertaler Gletscher),13.0,5.1,2.7,20,20.8
63,Moelltal Glacier (Mölltaler Gletscher),5.2,7.2,5.0,17,17.4
65,Gargellen,20.8,5.3,2.0,28,28.1
67,. Rauriser Hochalmbahnen – Rauris,15.0,12.5,5.0,32,32.5
70,. Gerlitzen,10.5,27.8,3.3,41,41.6
77,. Mönichkirchen/Mariensee,5.5,6.0,2.0,13,13.5
78,Sportgastein,3.5,13.2,1.5,18,18.2
80,. Rosshütte – Seefeld,11.4,5.9,1.0,18,18.3
81,Sonnenkopf – Klösterle,12.8,15.9,0.8,29,29.5

#### Analizamos los registros en los que el total de kilómetros no coincide con la suma de pistas fáciles, intermedias y difíciles para decidir si conviene corregir la variable original. Eliminamos la columna original y nos quedamos ocn la oclumna generada.

In [36]:
# Eliminar la columna original
df.drop(columns="Total Kms", inplace=True)

# Renombrar la columna calculada
df.rename(
    columns={"Total Kms Calculados": "Total Kms"},
    inplace=True
)

In [37]:
df[["Easy", "Intermediate", "Difficult", "Total Kms"]].head()

    Easy  Intermediate  Difficult  Total Kms
0  101.0          61.0       17.0      179.0
1   47.0         142.0       49.0      238.0
2  122.0         129.0       33.0      284.0
3  132.0         123.0       50.0      305.0
4   47.0         123.0       28.0      198.0

### Limpieza de los nombres de las estaciones

In [38]:
df["NameResort"].str.startswith(".").sum()

np.int64(254)

In [39]:
df["NameResort"] = df["NameResort"].str.lstrip(". ").str.strip()

In [40]:
df["NameResort"].head(20)

0                         KitzSki – Kitzbühel/Kirchberg
1                      Ischgl/Samnaun – Silvretta Arena
2                       SkiWelt Wilder Kaiser-Brixental
3                                           Ski Arlberg
4                                    Serfaus-Fiss-Ladis
5     Saalbach Hinterglemm Leogang Fieberbrunn (Skic...
6     Kaltenbach – Hochzillertal/Hochfügen (SKi-opti...
7     Zillertal Arena – Zell am Ziller/Gerlos/Königs...
8     Schladming – Planai/​Hochwurzen/​Hauser Kaibli...
9                                                Sölden
10                                   Silvretta Montafon
11            Mayrhofen – Penken/Ahorn/Rastkogel/Eggalm
12                                           Obertauern
13                          Gurgl – Obergurgl-Hochgurgl
14               Hochkönig – Maria Alm/Dienten/Mühlbach
15    Snow Space Salzburg – Flachau/Wagrain/St. Joha...
16                          Schmittenhöhe – Zell am See
17                      Wildkogel – Neukirchen/Bramberg
18                     Kitzsteinhorn/Maiskogel – Kaprun
19    Bad Gastein/Bad Hofgastein – Schlossalm/Angert...
Name: NameResort, dtype: str

### Revisión de las divisas

In [41]:
df["Currency"].value_counts(dropna=False)

Currency
-                          1952
European Euro              1473
US Dollar                   435
Japanese Yen                316
Swiss Franc                 284
Czech koruna                231
Canadian Dollar             197
Polish zloty                125
Norwegian krone             105
Swedish krona                95
UK Pound                     49
New Zealand Dollar           24
Romanian leu                 21
Chiliean Peso                16
Russian ruble                14
Argentine Peso               13
Chinese Yuan                 12
Bosnia convertible mark      11
Icelandic krona              10
Australian dollar            10
NaN                           9
Hungarian forint              9
South Korean won              8
Ukrainian hryvnia             7
Bulgarian Lev                 6
Turkish lira                  6
Danish Krone                  5
Serbian dinar                 4
Georgian Lari                 4
Croatian Kuna                 4
Lebanese pound                4
South African rand            3
Kyrgyzstani som               3
Macedonian denar              2
Kazakhstani tenge             2
Israeli new shekel            2
Iranian rial                  1
Armenian Dram                 1
Indian rupee                  1
United Arab Emerites          1
Azerbaijani manat             1
unknown                       1
Mongolian togrog              1
Name: count, dtype: int64

In [42]:
df[df["Currency"] == "-"][["NameResort", "Country", "Adult", "Currency"]].head(200)

                                    NameResort  Country Adult Currency
143      Hohe Wand Wiese – Vienna (High Hills)  Austria     0        -
145                     Alfaierlift – Gschnitz  Austria     0        -
155                 annerlbauerlifte-krieglach  Austria     0        -
159                           aschaulift-koppl  Austria     0        -
160                          astenberg-wiesing  Austria     0        -
...                                        ...      ...   ...      ...
1048                valbella-di-gallio-sisemol    Italy     0        -
1050                             valle-divedro    Italy     0        -
1052  valpelline-ollomont-heliski-grand-combin    Italy     0        -
1054                         villaggio-palumbo    Italy     0        -
1055                    weissenbach-alpinwellt    Italy     0        -

[200 rows x 4 columns]

In [43]:
df[df["Currency"] == "-"]["Country"].value_counts()

Country
Germany      331
Japan        281
Poland       129
China        121
Canada        92
            ...
Ireland        1
Egypt          1
Brazil         1
Namibia        1
Singapore      1
Name: count, Length: 83, dtype: int64

In [44]:
paises_sin_moneda = df[df["Currency"] == "-"]["Country"].unique()
paises_sin_moneda

<StringArray>
[                     'Austria',                  'Switzerland',
                        'Italy',                       'France',
                      'Finland',                        'Spain',
                     'Bulgaria',                       'Serbia',
                       'Norway',                       'Sweden',
                     'Slovakia',                      'Germany',
       'Bosnia and Herzegovina',               'Czech Republic',
                     'Slovenia',                   'Montenegro',
                       'Poland',              'Southern Russia',
                'Liechtenstein',                      'Ukraine',
               'North Caucasus',                  'Netherlands',
                       'Greece',                      'Iceland',
                      'Romania',               'United Kingdom',
             'Northwest Russia',                    'Macedonia',
                    'Lithuania',                      'Belgium',
                      'Denmark',                          'USA',
                         'Iran',                       'Turkey',
                        'Japan',                       'Russia',
                       'Canada',       'Volga Federal District',
                        'China',        'Ural Federal District',
                 'Turkmenistan',                   'Kazakhstan',
                   'Kyrgyzstan',                     'Armenia ',
                  'South Korea',                  'New Zealand',
                    'Greenland',                        'Chile',
                        'India',                      'Morocco',
                      'Siberia',                       'Latvia',
                      'Georgia',                      'Hungary',
                    'Argentina',         'United Arab Emirates',
                      'Croatia',                    'Australia',
                      'Albania',                       'Mexico',
                   'Uzbekistan',                      'Algeria',
                         'Iraq',                        'Qatar',
                      'Lebanon',                     'Malaysia',
 'Far Eastern Federal District',                        'Nepal',
                         'Peru',                  'North Korea',
                      'Estonia',                     'Thailand',
                      'Belarus',                     'Pakistan',
                 'South Africa',               'Central Russia',
                   'Azerbaijan',                      'Bahrain',
                      'Ireland',                        'Egypt',
                       'Brazil',                      'Namibia',
                    'Singapore']
Length: 83, dtype: str

In [45]:
df[
    (df["Country"].isin(paises_sin_moneda)) &
    (df["Currency"] != "-")
].groupby("Country")["Currency"].unique()

Country
Argentina                      [Argentine Peso]
Armenia                         [Armenian Dram]
Australia                   [Australian dollar]
Austria                         [European Euro]
Azerbaijan                  [Azerbaijani manat]
                                  ...
USA                                 [US Dollar]
Ukraine                     [Ukrainian hryvnia]
United Arab Emirates     [United Arab Emerites]
United Kingdom                       [UK Pound]
Ural Federal District           [Russian ruble]
Name: Currency, Length: 61, dtype: object

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5478 entries, 0 to 5477
Data columns (total 33 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   URL                                                         5478 non-null   str
 1   Rate                                                        3471 non-null   float64
 2   NameResort                                                  5478 non-null   str
 3   Stars                                                       413 non-null    float64
 4   Km Freeride                                                 480 non-null    float64
 5   Continent                                                   5469 non-null   str
 6   Country                                                     5469 non-null   str
 7   State/Province                                              5469 non-null   str
 8   Altitude                                                    5469 non-null   float64
 9   Easy                                                        5478 non-null   float64
 10  Intermediate                                                5478 non-null   float64
 11  Difficult                                                   5478 non-null   float64
 12  Adult                                                       5469 non-null   str
 13  Currency                                                    5469 non-null   str
 14  Ski resort size                                             3452 non-null   float64
 15  Slope offering, variety of runs                             3452 non-null   float64
 16  Lifts and cable cars                                        3452 non-null   float64
 17  Snow reliability                                            429 non-null    float64
 18  Access, on-site parking                                     429 non-null    float64
 19  Orientation (trail map, information boards, sign-postings)  429 non-null    float64
 20  Cleanliness and hygiene                                     429 non-null    float64
 21  Environmentally friendly ski operation                      429 non-null    float64
 22  Mountain restaurants, ski huts, gastronomy                  429 non-null    float64
 23  Après-ski                                                   429 non-null    float64
 24  Accommodation offering directly at the slopes and lifts     429 non-null    float64
 25  Families and children                                       429 non-null    float64
 26  Beginners                                                   429 non-null    float64
 27  Snow parks                                                  429 non-null    float64
 28  Cross-country skiing and trails                             429 non-null    float64
 29  country                                                     4879 non-null   str
 30  latitude                                                    4880 non-null   float64
 31  longitude                                                   4880 non-null   float64
 32  Total Kms                                                   5478 non-null   float64
dtypes: float64(25), str(8)
memory usage: 1.4 MB

In [47]:
moneda_por_pais = (
    df[
        (df["Currency"] != "-") &
        (df["Currency"].notna())
    ]
    .groupby("Country")["Currency"]
    .first()
    .to_dict()
)

In [48]:
df.loc[df["Currency"] == "-", "Currency"] = (
    df.loc[df["Currency"] == "-", "Country"].map(moneda_por_pais)
)

In [49]:
df["Currency"].isnull().sum()

np.int64(71)

In [50]:
df[df["Currency"].isna()][["NameResort", "Country", "Adult", "Currency"]].head(30)

,NameResort,Country,Adult,Currency
1830,Wildhaus – Gamserrugg (Toggenburg),NaN,NaN,NaN
1831,Ehrwalder Wettersteinbahnen – Ehrwald,NaN,NaN,NaN
1832,Ravna Planina,NaN,NaN,NaN
1833,Savin Kuk – Žabljak,NaN,NaN,NaN
1834,SnowWorld Rucphen (indoor ski area),NaN,NaN,NaN
1835,Raudalen,NaN,NaN,NaN
1836,SnowWorld Terneuzen (indoor ski area),NaN,NaN,NaN
1837,SnowWorld Amsterdam (indoor ski area),NaN,NaN,NaN
1838,Rölzhang – Wildenthal,NaN,NaN,NaN
5017,abzakovo,Volga Federal District,0,NaN
5018,khakaborazi-planned,Volga Federal District,0,NaN
5019,kush-tau,Volga Federal District,0,NaN
5020,magnitogorsk,Volga Federal District,0,NaN
5021,mratkino-beloretsk,Volga Federal District,0,NaN
5022,ski-komplex-sok-krasnaya-glinka,Volga Federal District,0,NaN
5165,ahal-ashgabat,Turkmenistan,0,NaN
5166,balkanabat,Turkmenistan,0,NaN
5167,dashoguz,Turkmenistan,0,NaN
5168,mary,Turkmenistan,0,NaN
5169,tuerkmenabat,Turkmenistan,0,NaN
5311,azrou,Morocco,0,NaN
5312,djebel-bou-iblane,Morocco,0,NaN
5313,hoher-atlas,Morocco,0,NaN
5314,jbel-hebri,Morocco,0,NaN
5315,michlifen,Morocco,0,NaN
5316,oukaimeden,Morocco,0,NaN
5317,rif-gebirge,Morocco,0,NaN
5407,bigell-dardhe,Albania,0,NaN
5408,puke,Albania,0,NaN
5409,bosques-de-monterreal-san-antonio-de-las-alazanas,Mexico,0,NaN

In [51]:
df[df["Currency"].isna()]["Country"].value_counts(dropna=False)

Country
Central Russia            11
NaN                        9
Morocco                    7
Volga Federal District     6
Turkmenistan               5
Uzbekistan                 4
Belarus                    4
Malaysia                   3
North Korea                3
Pakistan                   3
Albania                    2
Iraq                       2
Qatar                      2
Mexico                     1
Algeria                    1
Nepal                      1
Peru                       1
Thailand                   1
Bahrain                    1
Ireland                    1
Egypt                      1
Namibia                    1
Singapore                  1
Name: count, dtype: int64

In [52]:
monedas_manuales = {
    "Morocco": "Moroccan Dirham",
    "Central Russia": "Russian ruble",
    "Volga Federal District": "Russian ruble",
    "Turkmenistan": "Turkmenistani Manat",
    "Uzbekistan": "Uzbekistani Som",
    "Belarus": "Belarusian Ruble",
    "Malaysia": "Malaysian Ringgit",
    "North Korea": "North Korean Won",
    "Pakistan": "Pakistani Rupee",
    "Albania": "Albanian Lek",
    "Iraq": "Iraqi Dinar",
    "Qatar": "Qatari Riyal",
    "Mexico": "Mexican Peso",
    "Algeria": "Algerian Dinar",
    "Nepal": "Nepalese Rupee",
    "Peru": "Peruvian Sol",
    "Thailand": "Thai Baht",
    "Bahrain": "Bahraini Dinar",
    "Ireland": "European Euro",
    "Egypt": "Egyptian Pound",
    "Namibia": "Namibian Dollar",
    "Singapore": "Singapore Dollar"
}

In [53]:
mask = df["Currency"].isna()

df.loc[mask, "Currency"] = (
    df.loc[mask, "Country"].map(monedas_manuales)
)

In [54]:
df[df["Currency"].isna()]["Country"].value_counts(dropna=False)

Country
NaN    9
Name: count, dtype: int64

In [55]:
df[df["Country"].isna()]

,URL,Rate,NameResort,Stars,Km Freeride,Continent,Country,State/Province,Altitude,Easy,Intermediate,Difficult,Adult,Currency,Ski resort size,"Slope offering, variety of runs",Lifts and cable cars,Snow reliability,"Access, on-site parking","Orientation (trail map, information boards, sign-postings)",Cleanliness and hygiene,Environmentally friendly ski operation,"Mountain restaurants, ski huts, gastronomy",Après-ski,Accommodation offering directly at the slopes and lifts,Families and children,Beginners,Snow parks,Cross-country skiing and trails,country,latitude,longitude,Total Kms
1830,http://www.skiresort.info/ski-resort/wildhaus-...,3.9,Wildhaus – Gamserrugg (Toggenburg),3.0,12.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1831,http://www.skiresort.info/ski-resort/ehrwalder...,3.5,Ehrwalder Wettersteinbahnen – Ehrwald,2.0,1.5,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1832,http://www.skiresort.info/ski-resort/ravna-pla...,3.0,Ravna Planina,2.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1833,http://www.skiresort.info/ski-resort/savin-kuk...,2.9,Savin Kuk – Žabljak,3.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1834,http://www.skiresort.info/ski-resort/snowworld...,2.7,SnowWorld Rucphen (indoor ski area),1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1835,http://www.skiresort.info/ski-resort/raudalen/,NaN,Raudalen,3.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1836,http://www.skiresort.info/ski-resort/snowworld...,NaN,SnowWorld Terneuzen (indoor ski area),1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1837,http://www.skiresort.info/ski-resort/snowworld...,NaN,SnowWorld Amsterdam (indoor ski area),1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1838,http://www.skiresort.info/ski-resort/roelzhang...,NaN,Rölzhang – Wildenthal,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

#### Eliminamos estas 9 filas con muchos valos Nan o 0 y que por tanto no tenemos infromación como para poder incluirlas.

In [56]:
df = df[df["Country"].notna()].copy()

In [57]:
df["Country"].isna().sum()

np.int64(0)

In [58]:
df.info()

<class 'pandas.DataFrame'>
Index: 5469 entries, 0 to 5477
Data columns (total 33 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   URL                                                         5469 non-null   str
 1   Rate                                                        3466 non-null   float64
 2   NameResort                                                  5469 non-null   str
 3   Stars                                                       404 non-null    float64
 4   Km Freeride                                                 471 non-null    float64
 5   Continent                                                   5469 non-null   str
 6   Country                                                     5469 non-null   str
 7   State/Province                                              5469 non-null   str
 8   Altitude                                                    5469 non-null   float64
 9   Easy                                                        5469 non-null   float64
 10  Intermediate                                                5469 non-null   float64
 11  Difficult                                                   5469 non-null   float64
 12  Adult                                                       5469 non-null   str
 13  Currency                                                    5469 non-null   str
 14  Ski resort size                                             3452 non-null   float64
 15  Slope offering, variety of runs                             3452 non-null   float64
 16  Lifts and cable cars                                        3452 non-null   float64
 17  Snow reliability                                            429 non-null    float64
 18  Access, on-site parking                                     429 non-null    float64
 19  Orientation (trail map, information boards, sign-postings)  429 non-null    float64
 20  Cleanliness and hygiene                                     429 non-null    float64
 21  Environmentally friendly ski operation                      429 non-null    float64
 22  Mountain restaurants, ski huts, gastronomy                  429 non-null    float64
 23  Après-ski                                                   429 non-null    float64
 24  Accommodation offering directly at the slopes and lifts     429 non-null    float64
 25  Families and children                                       429 non-null    float64
 26  Beginners                                                   429 non-null    float64
 27  Snow parks                                                  429 non-null    float64
 28  Cross-country skiing and trails                             429 non-null    float64
 29  country                                                     4879 non-null   str
 30  latitude                                                    4880 non-null   float64
 31  longitude                                                   4880 non-null   float64
 32  Total Kms                                                   5469 non-null   float64
dtypes: float64(25), str(8)
memory usage: 1.4 MB

In [59]:
df["Adult"].head(20)

0        55
1        53
2        49
3        53
4        51
5        53
6     52,50
7        52
8     51,50
9        53
10    52,50
11       52
12    45,50
13       52
14    51,50
15    51,50
16       51
17       45
18       51
19       52
Name: Adult, dtype: str

In [60]:
df["Adult"].value_counts().head(20)

Adult
0     1952
15      95
20      93
18      79
25      72
35      70
10      70
30      69
12      66
22      62
16      58
14      53
45      47
19      47
28      44
17      44
40      43
32      43
39      42
13      40
Name: count, dtype: int64

In [61]:
df[df["Adult"] == "0"][
    ["NameResort", "Country", "Currency", "Adult", "Total Kms"]
].head(10)

,NameResort,Country,Currency,Adult,Total Kms
143,Hohe Wand Wiese – Vienna (High Hills),Austria,European Euro,0,0.5
145,Alfaierlift – Gschnitz,Austria,European Euro,0,0.5
155,annerlbauerlifte-krieglach,Austria,European Euro,0,0.5
159,aschaulift-koppl,Austria,European Euro,0,0.5
160,astenberg-wiesing,Austria,European Euro,0,1.0
161,astenlift-st-veit-im-pongau,Austria,European Euro,0,0.7
162,bachrain-golling-an-der-salzach,Austria,European Euro,0,0.5
165,baldramsdorf,Austria,European Euro,0,0.5
166,bameshub-neukirchen-am-waldeeschenau,Austria,European Euro,0,0.6
168,berger-anger-berg-im-drautal,Austria,European Euro,0,0.2

In [62]:
df[df["Adult"] == "0"]["Currency"].value_counts(dropna=False)

Currency
European Euro              603
Japanese Yen               281
Polish zloty               129
Chinese Yuan               121
Canadian Dollar             92
US Dollar                   87
Russian ruble               79
Romanian leu                72
Czech koruna                70
Swiss Franc                 52
Ukrainian hryvnia           41
UK Pound                    31
Turkish lira                30
Swedish krona               23
Serbian dinar               21
Indian rupee                21
Iranian rial                20
Kyrgyzstani som             18
New Zealand Dollar          16
Bulgarian Lev               14
Danish Krone                14
South Korean won            13
Norwegian krone              7
Moroccan Dirham              7
Macedonian denar             6
Argentine Peso               6
Croatian Kuna                6
Bosnia convertible mark      5
Turkmenistani Manat          5
Hungarian forint             5
United Arab Emerites         5
Australian dollar            5
Uzbekistani Som              4
Belarusian Ruble             4
Kazakhstani tenge            3
Lebanese pound               3
Malaysian Ringgit            3
North Korean Won             3
Pakistani Rupee              3
Armenian Dram                2
Georgian Lari                2
Albanian Lek                 2
Iraqi Dinar                  2
Qatari Riyal                 2
Icelandic krona              1
Chiliean Peso                1
Mexican Peso                 1
Algerian Dinar               1
Nepalese Rupee               1
Peruvian Sol                 1
Thai Baht                    1
South African rand           1
Azerbaijani manat            1
Bahraini Dinar               1
Egyptian Pound               1
unknown                      1
Namibian Dollar              1
Singapore Dollar             1
Name: count, dtype: int64

#### Convertimos en numérico la columna del precio del forfait

In [63]:
df["Adult"] = pd.to_numeric(df["Adult"], errors="coerce")

### Clasificación tamaño de las estaciones

#### Se crea una nueva columna que clasifica las estaciones según el total de kilómetros esquiables. Esta categorización facilitará la segmentación de los destinos y permitirá realizar comparaciones más representativas en el análisis.

In [64]:
def clasificar_tamano(km):
    if km < 5:
        return "Muy pequeña"
    elif km < 25:
        return "Pequeña"
    elif km < 75:
        return "Mediana"
    elif km < 150:
        return "Grande"
    else:
        return "Muy grande"

df["Tamaño estación"] = df["Total Kms"].apply(clasificar_tamano)

In [65]:
df["Tamaño estación"].value_counts()

Tamaño estación
Muy pequeña    3593
Pequeña        1291
Mediana         423
Grande          121
Muy grande       41
Name: count, dtype: int64

In [66]:
df[["NameResort", "Total Kms", "Tamaño estación"]].head(20)

,NameResort,Total Kms,Tamaño estación
0,KitzSki – Kitzbühel/Kirchberg,179.0,Muy grande
1,Ischgl/Samnaun – Silvretta Arena,238.0,Muy grande
2,SkiWelt Wilder Kaiser-Brixental,284.0,Muy grande
3,Ski Arlberg,305.0,Muy grande
4,Serfaus-Fiss-Ladis,198.0,Muy grande
5,Saalbach Hinterglemm Leogang Fieberbrunn (Skic...,270.0,Muy grande
6,Kaltenbach – Hochzillertal/Hochfügen (SKi-opti...,83.0,Grande
7,Zillertal Arena – Zell am Ziller/Gerlos/Königs...,143.0,Grande
8,Schladming – Planai/​Hochwurzen/​Hauser Kaibli...,123.0,Grande
9,Sölden,144.2,Grande
10,Silvretta Montafon,113.0,Grande
11,Mayrhofen – Penken/Ahorn/Rastkogel/Eggalm,136.0,Grande
12,Obertauern,100.0,Grande
13,Gurgl – Obergurgl-Hochgurgl,110.0,Grande
14,Hochkönig – Maria Alm/Dienten/Mühlbach,112.0,Grande
15,Snow Space Salzburg – Flachau/Wagrain/St. Joha...,115.0,Grande
16,Schmittenhöhe – Zell am See,77.0,Grande
17,Wildkogel – Neukirchen/Bramberg,64.0,Mediana
18,Kitzsteinhorn/Maiskogel – Kaprun,41.0,Mediana
19,Bad Gastein/Bad Hofgastein – Schlossalm/Angert...,86.0,Grande

### Clasificación del perfil recomendado

#### Se crea una nueva columna que clasifica cada estación según el tipo de pistas predominante. Esta información permitirá identificar el perfil de esquiador más adecuado para cada destino.

In [67]:
df["% Pistas fáciles"] = (df["Easy"] / df["Total Kms"]) * 100
df["% Pistas intermedias"] = (df["Intermediate"] / df["Total Kms"]) * 100
df["% Pistas difíciles"] = (df["Difficult"] / df["Total Kms"]) * 100

In [68]:
df.columns.tolist()

['URL',
 'Rate',
 'NameResort',
 'Stars',
 'Km Freeride',
 'Continent',
 'Country',
 'State/Province',
 'Altitude',
 'Easy',
 'Intermediate',
 'Difficult',
 'Adult',
 'Currency',
 'Ski resort size',
 'Slope offering, variety of runs',
 'Lifts and cable cars',
 'Snow reliability',
 'Access, on-site parking',
 'Orientation (trail map, information boards, sign-postings)',
 'Cleanliness and hygiene',
 'Environmentally friendly ski operation',
 'Mountain restaurants, ski huts, gastronomy',
 'Après-ski',
 'Accommodation offering directly at the slopes and lifts',
 'Families and children',
 'Beginners',
 'Snow parks',
 'Cross-country skiing and trails',
 'country',
 'latitude',
 'longitude',
 'Total Kms',
 'Tamaño estación',
 '% Pistas fáciles',
 '% Pistas intermedias',
 '% Pistas difíciles']

In [69]:
def clasificar_perfil(row):
    
    porcentajes = {
        "Principiante": row["% Pistas fáciles"],
        "Intermedio": row["% Pistas intermedias"],
        "Avanzado": row["% Pistas difíciles"]
    }
    
    # Ordenar porcentajes de mayor a menor
    ordenados = sorted(porcentajes.items(), key=lambda x: x[1], reverse=True)

    # Si la diferencia entre el primero y el segundo es menor de 10 puntos,
    # consideramos la estación equilibrada
    if ordenados[0][1] - ordenados[1][1] < 10:
        return "Equilibrada"

    return ordenados[0][0]


df["Perfil recomendado"] = df.apply(clasificar_perfil, axis=1)

In [70]:
df["Perfil recomendado"].value_counts()

Perfil recomendado
Principiante    3468
Intermedio      1132
Equilibrada      743
Avanzado         126
Name: count, dtype: int64

In [71]:
df[
    [
        "NameResort",
        "% Pistas fáciles",
        "% Pistas intermedias",
        "% Pistas difíciles",
        "Perfil recomendado"
    ]
].head(20)

,NameResort,% Pistas fáciles,% Pistas intermedias,% Pistas difíciles,Perfil recomendado
0,KitzSki – Kitzbühel/Kirchberg,56.424581,34.078212,9.497207,Principiante
1,Ischgl/Samnaun – Silvretta Arena,19.747899,59.663866,20.588235,Intermedio
2,SkiWelt Wilder Kaiser-Brixental,42.957746,45.422535,11.619718,Equilibrada
3,Ski Arlberg,43.278689,40.327869,16.393443,Equilibrada
4,Serfaus-Fiss-Ladis,23.737374,62.121212,14.141414,Intermedio
5,Saalbach Hinterglemm Leogang Fieberbrunn (Skic...,51.851852,41.481481,6.666667,Principiante
6,Kaltenbach – Hochzillertal/Hochfügen (SKi-opti...,34.578313,49.759036,15.662651,Intermedio
7,Zillertal Arena – Zell am Ziller/Gerlos/Königs...,30.069930,62.237762,7.692308,Intermedio
8,Schladming – Planai/​Hochwurzen/​Hauser Kaibli...,37.723577,55.528455,6.747967,Intermedio
9,Sölden,48.682386,30.929265,20.388350,Principiante
10,Silvretta Montafon,53.097345,39.823009,7.079646,Principiante
11,Mayrhofen – Penken/Ahorn/Rastkogel/Eggalm,29.411765,46.323529,24.264706,Intermedio
12,Obertauern,61.000000,35.000000,4.000000,Principiante
13,Gurgl – Obergurgl-Hochgurgl,31.818182,50.000000,18.181818,Intermedio
14,Hochkönig – Maria Alm/Dienten/Mühlbach,46.428571,36.607143,16.964286,Equilibrada
15,Snow Space Salzburg – Flachau/Wagrain/St. Joha...,26.086957,70.434783,3.478261,Intermedio
16,Schmittenhöhe – Zell am See,38.961039,36.363636,24.675325,Equilibrada
17,Wildkogel – Neukirchen/Bramberg,45.312500,39.062500,15.625000,Equilibrada
18,Kitzsteinhorn/Maiskogel – Kaprun,31.707317,60.975610,7.317073,Intermedio
19,Bad Gastein/Bad Hofgastein – Schlossalm/Angert...,35.581395,61.395349,3.023256,Intermedio

In [72]:
def clasificar_freeride(km):
    if pd.isna(km) or km == 0:
        return "Sin freeride"
    elif km <= 10:
        return "Freeride básico"
    elif km <= 30:
        return "Freeride avanzado"
    else:
        return "Para amantes del freeride"

df["Perfil freeride"] = df["Km Freeride"].apply(clasificar_freeride)

In [73]:
df["Perfil freeride"].value_counts()

Perfil freeride
Sin freeride                 5275
Freeride básico               178
Freeride avanzado              12
Para amantes del freeride       4
Name: count, dtype: int64

In [74]:
df[
    ["NameResort", "Km Freeride", "Perfil freeride"]
].head(20)

,NameResort,Km Freeride,Perfil freeride
0,KitzSki – Kitzbühel/Kirchberg,45.0,Para amantes del freeride
1,Ischgl/Samnaun – Silvretta Arena,15.0,Freeride avanzado
2,SkiWelt Wilder Kaiser-Brixental,26.0,Freeride avanzado
3,Ski Arlberg,200.0,Para amantes del freeride
4,Serfaus-Fiss-Ladis,28.0,Freeride avanzado
5,Saalbach Hinterglemm Leogang Fieberbrunn (Skic...,0.0,Sin freeride
6,Kaltenbach – Hochzillertal/Hochfügen (SKi-opti...,3.6,Freeride básico
7,Zillertal Arena – Zell am Ziller/Gerlos/Königs...,3.0,Freeride básico
8,Schladming – Planai/​Hochwurzen/​Hauser Kaibli...,4.0,Freeride básico
9,Sölden,0.0,Sin freeride
10,Silvretta Montafon,23.0,Freeride avanzado
11,Mayrhofen – Penken/Ahorn/Rastkogel/Eggalm,8.7,Freeride básico
12,Obertauern,0.0,Sin freeride
13,Gurgl – Obergurgl-Hochgurgl,4.5,Freeride básico
14,Hochkönig – Maria Alm/Dienten/Mühlbach,8.0,Freeride básico
15,Snow Space Salzburg – Flachau/Wagrain/St. Joha...,5.0,Freeride básico
16,Schmittenhöhe – Zell am See,8.0,Freeride básico
17,Wildkogel – Neukirchen/Bramberg,2.0,Freeride básico
18,Kitzsteinhorn/Maiskogel – Kaprun,0.5,Freeride básico
19,Bad Gastein/Bad Hofgastein – Schlossalm/Angert...,1.3,Freeride básico

### Cálculo del precio por kilómetro esquiable

In [75]:
df["Precio por km"] = (df["Adult"] / df["Total Kms"]).round(2)

In [76]:
df[["NameResort", "Adult", "Total Kms", "Precio por km"]].head(20)

,NameResort,Adult,Total Kms,Precio por km
0,KitzSki – Kitzbühel/Kirchberg,55.0,179.0,0.31
1,Ischgl/Samnaun – Silvretta Arena,53.0,238.0,0.22
2,SkiWelt Wilder Kaiser-Brixental,49.0,284.0,0.17
3,Ski Arlberg,53.0,305.0,0.17
4,Serfaus-Fiss-Ladis,51.0,198.0,0.26
5,Saalbach Hinterglemm Leogang Fieberbrunn (Skic...,53.0,270.0,0.20
6,Kaltenbach – Hochzillertal/Hochfügen (SKi-opti...,NaN,83.0,NaN
7,Zillertal Arena – Zell am Ziller/Gerlos/Königs...,52.0,143.0,0.36
8,Schladming – Planai/​Hochwurzen/​Hauser Kaibli...,NaN,123.0,NaN
9,Sölden,53.0,144.2,0.37
10,Silvretta Montafon,NaN,113.0,NaN
11,Mayrhofen – Penken/Ahorn/Rastkogel/Eggalm,52.0,136.0,0.38
12,Obertauern,NaN,100.0,NaN
13,Gurgl – Obergurgl-Hochgurgl,52.0,110.0,0.47
14,Hochkönig – Maria Alm/Dienten/Mühlbach,NaN,112.0,NaN
15,Snow Space Salzburg – Flachau/Wagrain/St. Joha...,NaN,115.0,NaN
16,Schmittenhöhe – Zell am See,51.0,77.0,0.66
17,Wildkogel – Neukirchen/Bramberg,45.0,64.0,0.70
18,Kitzsteinhorn/Maiskogel – Kaprun,51.0,41.0,1.24
19,Bad Gastein/Bad Hofgastein – Schlossalm/Angert...,52.0,86.0,0.60

In [77]:
df["Precio por km"].describe()

c:\Users\dieve\OneDrive\Escritorio\Ski Resort Analysis 2\Ski Resort Analysis\venv\Lib\site-packages\pandas\core\nanops.py:1028: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

count    4435.000
mean          inf
std           NaN
min         0.000
25%         0.000
50%         4.440
75%        30.515
max           inf
Name: Precio por km, dtype: float64

In [78]:
df.info()

<class 'pandas.DataFrame'>
Index: 5469 entries, 0 to 5477
Data columns (total 40 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   URL                                                         5469 non-null   str
 1   Rate                                                        3466 non-null   float64
 2   NameResort                                                  5469 non-null   str
 3   Stars                                                       404 non-null    float64
 4   Km Freeride                                                 471 non-null    float64
 5   Continent                                                   5469 non-null   str
 6   Country                                                     5469 non-null   str
 7   State/Province                                              5469 non-null   str
 8   Altitude                                                    5469 non-null   float64
 9   Easy                                                        5469 non-null   float64
 10  Intermediate                                                5469 non-null   float64
 11  Difficult                                                   5469 non-null   float64
 12  Adult                                                       5136 non-null   float64
 13  Currency                                                    5469 non-null   str
 14  Ski resort size                                             3452 non-null   float64
 15  Slope offering, variety of runs                             3452 non-null   float64
 16  Lifts and cable cars                                        3452 non-null   float64
 17  Snow reliability                                            429 non-null    float64
 18  Access, on-site parking                                     429 non-null    float64
 19  Orientation (trail map, information boards, sign-postings)  429 non-null    float64
 20  Cleanliness and hygiene                                     429 non-null    float64
 21  Environmentally friendly ski operation                      429 non-null    float64
 22  Mountain restaurants, ski huts, gastronomy                  429 non-null    float64
 23  Après-ski                                                   429 non-null    float64
 24  Accommodation offering directly at the slopes and lifts     429 non-null    float64
 25  Families and children                                       429 non-null    float64
 26  Beginners                                                   429 non-null    float64
 27  Snow parks                                                  429 non-null    float64
 28  Cross-country skiing and trails                             429 non-null    float64
 29  country                                                     4879 non-null   str
 30  latitude                                                    4880 non-null   float64
 31  longitude                                                   4880 non-null   float64
 32  Total Kms                                                   5469 non-null   float64
 33  Tamaño estación                                             5469 non-null   str
 34  % Pistas fáciles                                            4619 non-null   float64
 35  % Pistas intermedias                                        4619 non-null   float64
 36  % Pistas difíciles                                          4619 non-null   float64
 37  Perfil recomendado                                          5469 non-null   str
 38  Perfil freeride                                             5469 non-null   str
 39  Precio por km                                               4435 non-null   float64
dtypes: float64(30), str(10)
memory usage: 1.7 MB

In [79]:
nulos = pd.DataFrame({
    "Nulos": df.isnull().sum(),
    "Porcentaje (%)": round(df.isnull().mean() * 100, 2)
})

nulos = nulos[nulos["Nulos"] > 0].sort_values(by="Nulos", ascending=False)

nulos

                                                    Nulos  Porcentaje (%)
Stars                                                5065           92.61
Access, on-site parking                              5040           92.16
Snow reliability                                     5040           92.16
Orientation (trail map, information boards, sig...   5040           92.16
Families and children                                5040           92.16
Accommodation offering directly at the slopes a...   5040           92.16
Après-ski                                            5040           92.16
Mountain restaurants, ski huts, gastronomy           5040           92.16
Environmentally friendly ski operation               5040           92.16
Cleanliness and hygiene                              5040           92.16
Cross-country skiing and trails                      5040           92.16
Snow parks                                           5040           92.16
Beginners                                            5040           92.16
Km Freeride                                          4998           91.39
Ski resort size                                      2017           36.88
Lifts and cable cars                                 2017           36.88
Slope offering, variety of runs                      2017           36.88
Rate                                                 2003           36.62
Precio por km                                        1034           18.91
% Pistas difíciles                                    850           15.54
% Pistas fáciles                                      850           15.54
% Pistas intermedias                                  850           15.54
country                                               590           10.79
longitude                                             589           10.77
latitude                                              589           10.77
Adult                                                 333            6.09

In [80]:
df["Km Freeride"] = df["Km Freeride"].fillna(0)

In [81]:
df[["Country", "country"]].head(20)

    Country country
0   Austria      AT
1   Austria      AT
2   Austria      AT
3   Austria      AT
4   Austria      AT
5   Austria      AT
6   Austria      AT
7   Austria      AT
8   Austria      AT
9   Austria      AT
10  Austria      AT
11  Austria      AT
12  Austria      AT
13  Austria      AT
14  Austria      AT
15  Austria      AT
16  Austria      AT
17  Austria      AT
18  Austria      AT
19  Austria      AT

In [82]:
df.rename(columns={"country": "Country Code"}, inplace=True)

In [83]:
df["Km Freeride"].isna().sum()

np.int64(0)

#### Eliminamos columna Stars

In [84]:
df.drop(columns="Stars", inplace=True)

In [85]:
df.columns

Index(['URL', 'Rate', 'NameResort', 'Km Freeride', 'Continent', 'Country',
       'State/Province', 'Altitude', 'Easy', 'Intermediate', 'Difficult',
       'Adult', 'Currency', 'Ski resort size',
       'Slope offering, variety of runs', 'Lifts and cable cars',
       'Snow reliability', 'Access, on-site parking',
       'Orientation (trail map, information boards, sign-postings)',
       'Cleanliness and hygiene', 'Environmentally friendly ski operation',
       'Mountain restaurants, ski huts, gastronomy', 'Après-ski',
       'Accommodation offering directly at the slopes and lifts',
       'Families and children', 'Beginners', 'Snow parks',
       'Cross-country skiing and trails', 'Country Code', 'latitude',
       'longitude', 'Total Kms', 'Tamaño estación', '% Pistas fáciles',
       '% Pistas intermedias', '% Pistas difíciles', 'Perfil recomendado',
       'Perfil freeride', 'Precio por km'],
      dtype='str')

In [86]:
nulos = pd.DataFrame({
    "Nulos": df.isnull().sum(),
    "Porcentaje (%)": round(df.isnull().mean() * 100, 2)
})

nulos = nulos[nulos["Nulos"] > 0].sort_values(by="Nulos", ascending=False)

nulos

                                                    Nulos  Porcentaje (%)
Access, on-site parking                              5040           92.16
Orientation (trail map, information boards, sig...   5040           92.16
Snow reliability                                     5040           92.16
Accommodation offering directly at the slopes a...   5040           92.16
Après-ski                                            5040           92.16
Mountain restaurants, ski huts, gastronomy           5040           92.16
Environmentally friendly ski operation               5040           92.16
Cleanliness and hygiene                              5040           92.16
Cross-country skiing and trails                      5040           92.16
Families and children                                5040           92.16
Beginners                                            5040           92.16
Snow parks                                           5040           92.16
Slope offering, variety of runs                      2017           36.88
Ski resort size                                      2017           36.88
Lifts and cable cars                                 2017           36.88
Rate                                                 2003           36.62
Precio por km                                        1034           18.91
% Pistas difíciles                                    850           15.54
% Pistas fáciles                                      850           15.54
% Pistas intermedias                                  850           15.54
Country Code                                          590           10.79
longitude                                             589           10.77
latitude                                              589           10.77
Adult                                                 333            6.09

#### Los valores nulos de la variable `Adult` se imputan utilizando la mediana del precio de forfait de estaciones con características similares. Para ello se consideran el país, la categoría de tamaño de la estación y el perfil recomendado. Este enfoque permite conservar la coherencia de los datos evitando el uso de medias globales que podrían distorsionar los resultados.

In [87]:
df[df["Adult"].isna()][
    ["NameResort", "Country", "Total Kms", "Rate", "Currency"]
].head(30)

,NameResort,Country,Total Kms,Rate,Currency
6,Kaltenbach – Hochzillertal/Hochfügen (SKi-opti...,Austria,83.0,4.7,European Euro
8,Schladming – Planai/​Hochwurzen/​Hauser Kaibli...,Austria,123.0,4.7,European Euro
10,Silvretta Montafon,Austria,113.0,4.6,European Euro
12,Obertauern,Austria,100.0,4.5,European Euro
14,Hochkönig – Maria Alm/Dienten/Mühlbach,Austria,112.0,4.5,European Euro
15,Snow Space Salzburg – Flachau/Wagrain/St. Joha...,Austria,115.0,4.5,European Euro
20,Katschberg,Austria,70.0,4.3,European Euro
22,Ski Juwel Alpbachtal Wildschönau,Austria,93.1,4.2,European Euro
25,Großglockner Resort Kals-Matrei,Austria,37.0,4.2,European Euro
30,Großarltal/Dorfgastein,Austria,70.1,4.1,European Euro
31,Zauchensee/Flachauwinkl,Austria,44.0,4.1,European Euro
34,Golm,Austria,26.5,4.0,European Euro
36,St. Johann in Tirol/Oberndorf – Harschbichl,Austria,43.0,4.0,European Euro
37,Radstadt/Altenmarkt,Austria,17.0,4.0,European Euro
40,Dachstein West – Gosau/Russbach/Annaberg,Austria,51.0,4.0,European Euro
42,Sillian – Thurntaler (Hochpustertal),Austria,21.7,3.9,European Euro
44,Spieljoch – Fügen,Austria,21.1,3.9,European Euro
45,Kreischberg,Austria,42.0,3.9,European Euro
47,Hinterstoder – Höss,Austria,40.0,3.9,European Euro
48,Axamer Lizum,Austria,30.0,3.8,European Euro
49,St. Jakob im Defereggental – Brunnalm,Austria,17.0,3.8,European Euro
53,Brandnertal – Brand/Bürserberg,Austria,55.0,3.8,European Euro
55,Schlick 2000 – Fulpmes,Austria,22.0,3.7,European Euro
56,See,Austria,41.0,3.7,European Euro
62,Bergeralm – Steinach am Brenner,Austria,29.0,3.7,European Euro
63,Moelltal Glacier (Mölltaler Gletscher),Austria,17.4,3.7,European Euro
65,Gargellen,Austria,28.1,3.7,European Euro
67,Rauriser Hochalmbahnen – Rauris,Austria,32.5,3.7,European Euro
69,Flachauwinkl/Kleinarl (Shuttleberg),Austria,28.0,3.7,European Euro
71,Kappl,Austria,40.0,3.7,European Euro

In [88]:
df[df["Adult"].isna()]["Country"].value_counts().head(20)

Country
Austria           111
France             89
Canada             48
Germany            40
United Kingdom     13
Italy              11
Netherlands         5
Slovakia            4
Finland             3
Slovenia            3
USA                 2
Switzerland         1
Andorra             1
Spain               1
Brazil              1
Name: count, dtype: int64

In [89]:
df[df["Adult"].isna()][
    ["NameResort", "Country", "Total Kms", "Rate", "Tamaño estación"]
].sort_values("Total Kms", ascending=False).head(30)

,NameResort,Country,Total Kms,Rate,Tamaño estación
1070,Les Sybelles – Le Corbier/La Toussuire/Les Bot...,France,310.5,4.0,Muy grande
1064,Megève/Saint-Gervais,France,263.0,4.1,Muy grande
1059,Serre Chevalier – Briançon/Chantemerle/Villene...,France,250.5,4.4,Muy grande
1063,Alpe d'Huez,France,250.0,4.2,Muy grande
1067,Espace Diamant – Les Saisies/Notre-Dame-de-Bel...,France,192.0,4.1,Muy grande
1071,varsrisoul-la-foret-blanche,France,185.0,3.9,Muy grande
1072,le-grand-domaine-valmoreldoucycelliersst-franc...,France,165.0,3.9,Muy grande
1074,espace-san-bernardo-la-rosierela-thuile,France,160.0,3.9,Muy grande
1394,Baqueira/Beret,Spain,152.0,4.2,Muy grande
1073,galibier-thabor-valmeiniervalloire,France,150.0,3.9,Muy grande
4793,fernie,Canada,142.0,4.0,Grande
1085,Auron (Saint-Etienne-de-Tinée),France,135.0,3.6,Grande
1078,la-clusazmanigod,France,125.0,3.8,Grande
1079,espace-villard-correncon-villard-de-lanscorren...,France,125.0,3.8,Grande
1075,val-cenis-lanslevillardlanslebourgtermignon,France,125.0,3.8,Grande
8,Schladming – Planai/​Hochwurzen/​Hauser Kaibli...,Austria,123.0,4.7,Grande
1076,les-contamineshauteluce,France,120.0,3.8,Grande
1081,Isola 2000,France,120.0,3.7,Grande
15,Snow Space Salzburg – Flachau/Wagrain/St. Joha...,Austria,115.0,4.5,Grande
10,Silvretta Montafon,Austria,113.0,4.6,Grande
14,Hochkönig – Maria Alm/Dienten/Mühlbach,Austria,112.0,4.5,Grande
4821,kicking-horse-golden,Canada,100.0,3.0,Grande
12,Obertauern,Austria,100.0,4.5,Grande
1088,devoluy-superdevoluyla-joue-du-loup,France,100.0,3.6,Grande
1087,les-orres,France,100.0,3.6,Grande
22,Ski Juwel Alpbachtal Wildschönau,Austria,93.1,4.2,Grande
1089,chamrousse,France,90.0,3.6,Grande
1096,valbergbeuil-les-launes,France,90.0,3.4,Grande
1094,le-grand-bornand,France,86.0,3.5,Grande
6,Kaltenbach – Hochzillertal/Hochfügen (SKi-opti...,Austria,83.0,4.7,Grande

In [90]:
df.groupby("Tamaño estación")["Adult"].agg(["count", "mean", "median"])

                 count         mean  median
Tamaño estación
Grande              98  1087.877551    79.5
Mediana            366  1107.724044    52.0
Muy grande          31    83.903226    55.0
Muy pequeña       3467   250.273147     0.0
Pequeña           1174  2328.516184    40.0

In [91]:
df.groupby("Tamaño estación")["Adult"].agg(["count", "mean", "median"])

                 count         mean  median
Tamaño estación
Grande              98  1087.877551    79.5
Mediana            366  1107.724044    52.0
Muy grande          31    83.903226    55.0
Muy pequeña       3467   250.273147     0.0
Pequeña           1174  2328.516184    40.0

In [92]:
df["Adult"].describe()

count    5.136000e+03
mean     8.014048e+02
std      1.612215e+04
min      0.000000e+00
25%      0.000000e+00
50%      1.800000e+01
75%      5.800000e+01
max      1.119000e+06
Name: Adult, dtype: float64

In [93]:
medianas = (
    df.groupby(
        ["Country", "Tamaño estación", "Perfil recomendado"]
    )["Adult"]
    .transform("median")
)

df["Adult"] = df["Adult"].fillna(medianas)

In [94]:
df["Adult"].isna().sum()

np.int64(6)

In [95]:
medianas_pais_tamano = (
    df.groupby(
        ["Country", "Tamaño estación"]
    )["Adult"]
    .transform("median")
)

df["Adult"] = df["Adult"].fillna(medianas_pais_tamano)

In [96]:
df["Adult"].isna().sum()

np.int64(3)

In [97]:
df[df["Adult"].isna()][
    ["NameResort", "Country", "Total Kms", "Tamaño estación", "Perfil recomendado"]
]

          NameResort  Country  Total Kms Tamaño estación Perfil recomendado
1311            Levi  Finland       37.9         Mediana        Equilibrada
1312           Ylläs  Finland       55.0         Mediana         Intermedio
1394  Baqueira/Beret    Spain      152.0      Muy grande       Principiante

In [98]:
df[
    (df["Country"] == "Spain") &
    (df["Tamaño estación"] == "Muy grande") &
    (df["Adult"].notna())
][["NameResort", "Adult", "Total Kms"]]

Empty DataFrame
Columns: [NameResort, Adult, Total Kms]
Index: []

In [99]:
df[
    (df["Country"] == "Finland") &
    (df["Adult"].notna())
][["NameResort", "Adult", "Total Kms", "Perfil recomendado"]]

                  NameResort  Adult  Total Kms Perfil recomendado
1313                    Pyhä   44.0       11.4        Equilibrada
1314                    Ruka   44.0       18.9       Principiante
1315  Ounasvaara – Rovaniemi   38.0        4.5        Equilibrada
1316               aavasaksa   10.0        2.0       Principiante
1317               alhovuori    0.0        3.5       Principiante
...                      ...    ...        ...                ...
1388                 vatuski    0.0        0.0       Principiante
1389              vierumaeki    0.0        0.0       Principiante
1390        vihti-ski-center   34.0        3.0       Principiante
1391                vuokatti   39.0       10.0       Principiante
1392               vuorenmaa    0.0        0.0       Principiante

[80 rows x 4 columns]

In [100]:
df[
    (df["Country"] == "Finland") &
    (df["Tamaño estación"] == "Mediana") &
    (df["Perfil recomendado"] == "Equilibrada")
]

,URL,Rate,NameResort,Km Freeride,Continent,Country,State/Province,Altitude,Easy,Intermediate,Difficult,Adult,Currency,Ski resort size,"Slope offering, variety of runs",Lifts and cable cars,Snow reliability,"Access, on-site parking","Orientation (trail map, information boards, sign-postings)",Cleanliness and hygiene,Environmentally friendly ski operation,"Mountain restaurants, ski huts, gastronomy",Après-ski,Accommodation offering directly at the slopes and lifts,Families and children,Beginners,Snow parks,Cross-country skiing and trails,Country Code,latitude,longitude,Total Kms,Tamaño estación,% Pistas fáciles,% Pistas intermedias,% Pistas difíciles,Perfil recomendado,Perfil freeride,Precio por km
1311,http://www.skiresort.info/ski-resort/levi/,4.3,Levi,6.2,Europe,Finland,Northern Finland,531.0,15.7,19.4,2.8,NaN,European Euro,3.0,4.0,3.0,5.0,4.0,5.0,4.0,4.0,3.0,4.0,5.0,5.0,5.0,5.0,5.0,FI,61.92411,25.748151,37.9,Mediana,41.424802,51.187335,7.387863,Equilibrada,Freeride básico,NaN

In [101]:
df[
    (df["Tamaño estación"] == "Muy grande") &
    (df["Perfil recomendado"] == "Principiante") &
    (df["Adult"].notna())
][["NameResort", "Country", "Adult", "Total Kms"]]

,NameResort,Country,Adult,Total Kms
0,KitzSki – Kitzbühel/Kirchberg,Austria,55.0,179.0
5,Saalbach Hinterglemm Leogang Fieberbrunn (Skic...,Austria,53.0,270.0
433,Arosa Lenzerheide,Switzerland,75.0,225.0
443,Les Portes du Soleil – Morzine/Avoriaz/Les Get...,Switzerland,52.0,580.0
1057,Les 3 Vallées – Val Thorens/Les Menuires/Mérib...,France,61.0,600.0
1058,Tignes/Val d'Isère,France,57.0,300.0
1059,Serre Chevalier – Briançon/Chantemerle/Villene...,France,52.0,250.5
1060,La Plagne (Paradiski),France,52.0,225.0
1061,Les 2 Alpes,France,50.0,200.0
1065,Les Arcs/Peisey-Vallandry (Paradiski),France,52.0,200.0
1066,Le Grand Massif – Flaine/Les Carroz/Morillon/S...,France,47.0,265.0
1067,Espace Diamant – Les Saisies/Notre-Dame-de-Bel...,France,52.0,192.0
1072,le-grand-domaine-valmoreldoucycelliersst-franc...,France,52.0,165.0
1073,galibier-thabor-valmeiniervalloire,France,52.0,150.0
1308,Grandvalira – Pas de la Casa/Grau Roig/Soldeu/...,Andorra,49.0,210.0

In [102]:
precio_baqueira = df[
    (df["Tamaño estación"] == "Muy grande") &
    (df["Perfil recomendado"] == "Principiante") &
    (df["Adult"].notna())
]["Adult"].median()

precio_baqueira

np.float64(52.0)

In [103]:
df.loc[df["NameResort"] == "Levi", "Adult"] = 44
df.loc[df["NameResort"] == "Ylläs", "Adult"] = 44
df.loc[df["NameResort"] == "Baqueira/Beret", "Adult"] = precio_baqueira

In [104]:
df[df["NameResort"].isin(["Levi", "Ylläs", "Baqueira/Beret"])][
    ["NameResort", "Country", "Adult", "Total Kms", "Tamaño estación", "Perfil recomendado"]
]

,NameResort,Country,Adult,Total Kms,Tamaño estación,Perfil recomendado
1311,Levi,Finland,44.0,37.9,Mediana,Equilibrada
1312,Ylläs,Finland,44.0,55.0,Mediana,Intermedio
1394,Baqueira/Beret,Spain,52.0,152.0,Muy grande,Principiante

In [105]:
df["Adult"].isna().sum()

np.int64(0)

#### Tras la imputación automática basada en estaciones similares, permanecían tres estaciones relevantes sin información de precio del forfait. Debido a su importancia dentro del análisis, se completaron utilizando el precio de estaciones con características comparables, considerando el país, el tamaño de la estación y el perfil recomendado.

In [106]:
nulos = pd.DataFrame({
    "Nulos": df.isnull().sum(),
    "Porcentaje (%)": round(df.isnull().mean() * 100, 2)
})

nulos = nulos[nulos["Nulos"] > 0].sort_values("Nulos", ascending=False)

nulos

                                                    Nulos  Porcentaje (%)
Orientation (trail map, information boards, sig...   5040           92.16
Access, on-site parking                              5040           92.16
Snow reliability                                     5040           92.16
Après-ski                                            5040           92.16
Mountain restaurants, ski huts, gastronomy           5040           92.16
Environmentally friendly ski operation               5040           92.16
Cleanliness and hygiene                              5040           92.16
Cross-country skiing and trails                      5040           92.16
Families and children                                5040           92.16
Beginners                                            5040           92.16
Snow parks                                           5040           92.16
Accommodation offering directly at the slopes a...   5040           92.16
Lifts and cable cars                                 2017           36.88
Slope offering, variety of runs                      2017           36.88
Ski resort size                                      2017           36.88
Rate                                                 2003           36.62
Precio por km                                        1034           18.91
% Pistas fáciles                                      850           15.54
% Pistas intermedias                                  850           15.54
% Pistas difíciles                                    850           15.54
Country Code                                          590           10.79
longitude                                             589           10.77
latitude                                              589           10.77

### Valores Nulos de Longitude y Latitude

In [107]:
df[["latitude", "longitude"]].isna().sum()

latitude     589
longitude    589
dtype: int64

In [108]:
(
    df["latitude"].isna() == df["longitude"].isna()
).all()

np.True_

In [109]:
df[df["latitude"].isna()][
    ["NameResort", "Country", "State/Province", "Total Kms", "Tamaño estación", "Rate"]
].sort_values("Total Kms", ascending=False).head(30)

,NameResort,Country,State/Province,Total Kms,Tamaño estación,Rate
3845,park-city,USA,Utah,250.0,Muy grande,4.8
3568,big-sky-resort,USA,Montana,250.0,Muy grande,4.9
3934,snowmass,USA,Colorado,236.2,Muy grande,5.0
3999,vail,USA,Colorado,234.0,Muy grande,5.0
3949,steamboat,USA,Colorado,165.0,Muy grande,4.8
3596,breckenridge,USA,Colorado,153.0,Muy grande,4.0
3558,beaver-creek,USA,Colorado,150.0,Muy grande,4.0
4027,winter-park-resort,USA,Colorado,143.0,Grande,4.0
3542,aspen-highlands,USA,Colorado,135.0,Grande,4.0
3865,powder-mountain,USA,Utah,135.0,Grande,4.5
3736,keystone,USA,Colorado,135.0,Grande,4.0
3737,killington,USA,Vermont,126.4,Grande,4.4
3644,copper-mountain,USA,Colorado,126.0,Grande,4.4
3649,crested-butte,USA,Colorado,121.0,Grande,4.3
3959,sugarloaf,USA,Maine,119.0,Grande,4.3
3727,jackson-hole,USA,Wyoming,116.0,Grande,4.4
3529,alta,USA,Utah,116.0,Grande,4.3
3973,taos,USA,New Mexico,113.0,Grande,4.2
3540,arapahoe-basin,USA,Colorado,105.0,Grande,3.0
3543,aspen-mountain,USA,Colorado,103.0,Grande,3.0
3932,snowbird,USA,Utah,103.0,Grande,4.1
4010,wenatchee-mission-ridge,USA,Washington State,100.0,Grande,4.0
4032,wolf-creek,USA,Colorado,100.0,Grande,3.9
3524,alpine-meadows,USA,Western United States,100.0,Grande,3.0
3946,squaw-valley,USA,Western United States,100.0,Grande,4.0
3798,mt-baker,USA,Washington State,100.0,Grande,3.9
3655,deer-valley,USA,Utah,100.0,Grande,4.0
3815,mt-rose,USA,Western United States,100.0,Grande,4.0
3796,mt-bachelor,USA,Oregon,100.0,Grande,4.1
3832,northstar-california-resort,USA,Western United States,97.0,Grande,4.0

In [110]:
df[df["latitude"].isna()]["Country"].value_counts().head(20)

Country
USA                             521
Central Russia                   11
Northwest Russia                  9
North Caucasus                    8
Macedonia                         8
Ural Federal District             8
Siberia                           7
Volga Federal District            6
Southern Russia                   5
Armenia                           3
Far Eastern Federal District      3
Name: count, dtype: int64

In [111]:
df.loc[
    (df["Country"] == "USA") & (df["latitude"].isna()),
    ["latitude", "longitude"]
] = [39.8283, -98.5795]

In [112]:
df.loc[
    (df["Country"].str.contains("Russia", na=False)) & (df["latitude"].isna()),
    ["latitude", "longitude"]
] = [61.5240, 105.3188]

In [113]:
df[["latitude", "longitude"]].isna().sum()

latitude     43
longitude    43
dtype: int64

#### Se completan las coordenadas nulas de Estados Unidos y regiones rusas utilizando coordenadas aproximadas a nivel país. Esta imputación se realiza únicamente para facilitar la representación cartográfica en Power BI, manteniendo la interpretación de estos puntos como ubicaciones aproximadas y no como coordenadas exactas de las estaciones.

### Valores Nulos de Country Code

In [114]:
df["Country Code"].isna().sum()

np.int64(590)

In [115]:
df[
    df["Country Code"].isna()
][["Country", "latitude", "longitude"]].head()

              Country  latitude  longitude
3178  Southern Russia    61.524   105.3188
3179  Southern Russia    61.524   105.3188
3180  Southern Russia    61.524   105.3188
3181  Southern Russia    61.524   105.3188
3182  Southern Russia    61.524   105.3188

In [116]:
(
    df["Country Code"].isna()
    ==
    df["latitude"].isna()
).all()

np.False_

In [117]:
df.groupby("Country")["Country Code"].unique()

Country
Albania                    [AL]
Algeria                    [DZ]
Andorra                    [AD]
Argentina                  [AR]
Armenia                   [nan]
                          ...
United Arab Emirates       [AE]
United Kingdom             [GB]
Ural Federal District     [nan]
Uzbekistan                 [UZ]
Volga Federal District    [nan]
Name: Country Code, Length: 90, dtype: object

In [118]:
mapa_codigos = (
    df.dropna(subset=["Country Code"])
      .groupby("Country")["Country Code"]
      .first()
      .to_dict()
)

df["Country Code"] = df["Country Code"].fillna(
    df["Country"].map(mapa_codigos)
)

In [119]:
df["Country Code"].isna().sum()

np.int64(590)

In [120]:
codigos_manuales = {
    "USA": "US",
    "Southern Russia": "RU",
    "Central Russia": "RU",
    "Northwest Russia": "RU",
    "North Caucasus": "RU",
    "Ural Federal District": "RU",
    "Siberia": "RU",
    "Volga Federal District": "RU",
    "Far Eastern Federal District": "RU",
    "Armenia": "AM",
    "Macedonia": "MK"
}

df["Country Code"] = df["Country Code"].fillna(
    df["Country"].map(codigos_manuales)
)

In [121]:
df["Country Code"].isna().sum()

np.int64(4)

In [122]:
df[df["Country Code"].isna()][
    ["NameResort", "Country", "Country Code"]
]

          NameResort   Country Country Code
5196  akhtamar-sevan  Armenia           NaN
5197          jermuk  Armenia           NaN
5198     tsakhkadzor  Armenia           NaN
5474     ski-namibia   Namibia          NaN

In [123]:
codigos_manuales.update({
    "Armenia": "AM",
    "Namibia": "NA"
})

df["Country Code"] = df["Country Code"].fillna(
    df["Country"].map(codigos_manuales)
)

In [124]:
df["Country Code"].isna().sum()

np.int64(3)

In [125]:
df[df["Country Code"].isna()][
    ["NameResort", "Country", "Country Code"]
]

          NameResort   Country Country Code
5196  akhtamar-sevan  Armenia           NaN
5197          jermuk  Armenia           NaN
5198     tsakhkadzor  Armenia           NaN

In [126]:
df.loc[df["Country"] == "Armenia", "Country Code"] = "AM"

In [127]:
df["Country Code"].isna().sum()

np.int64(3)

In [128]:
df.loc[df["Country"].str.strip() == "Armenia", "Country Code"] = "AM"

In [129]:
df[df["Country Code"].isna()][["NameResort", "Country", "Country Code"]]

Empty DataFrame
Columns: [NameResort, Country, Country Code]
Index: []

In [130]:
df["Country Code"].isna().sum()

np.int64(0)

#### Se completaron los valores nulos de Country Code asignando el código ISO correspondiente a cada país o región. Tras esta corrección, la columna quedó libre de valores nulos.

### Valores nulos en % Pistas Fáciles, Difíciles e Intermedias

In [131]:
(df["Total Kms"] == 0).sum()

np.int64(850)

In [132]:
df[
    df["% Pistas fáciles"].isna()
][["NameResort", "Easy", "Intermediate", "Difficult", "Total Kms"]].head(20)

                    NameResort  Easy  Intermediate  Difficult  Total Kms
547            bernina-heliski   0.0           0.0        0.0        0.0
606                  haldigrat   0.0           0.0        0.0        0.0
689      pischa-davos-klosters   0.0           0.0        0.0        0.0
713         saentis-schwaegalp   0.0           0.0        0.0        0.0
865            chiomonte-frais   0.0           0.0        0.0        0.0
874  alpe-cainallo-esino-lario   0.0           0.0        0.0        0.0
876         alpe-devero-baceno   0.0           0.0        0.0        0.0
882                   bagolino   0.0           0.0        0.0        0.0
884           barco-del-sangro   0.0           0.0        0.0        0.0
900  castiglione-di-garfagnana   0.0           0.0        0.0        0.0
902              cerreto-laghi   0.0           0.0        0.0        0.0
905                  cima-ekar   0.0           0.0        0.0        0.0
911         conserva-di-lauria   0.0           0.0        0.0        0.0
912    croce-daune-monte-avena   0.0           0.0        0.0        0.0
913                      crodo   0.0           0.0        0.0        0.0
915                 domobianca   0.0           0.0        0.0        0.0
917                      edolo   0.0           0.0        0.0        0.0
918                    emarsee   0.0           0.0        0.0        0.0
919                  entracque   0.0           0.0        0.0        0.0
923                  etroubles   0.0           0.0        0.0        0.0

#### Los valores nulos de las variables `% Pistas fáciles`, `% Pistas intermedias` y `% Pistas difíciles` corresponden a estaciones con `Total Kms = 0`. Dado que no es posible calcular la distribución porcentual de pistas cuando no existen kilómetros esquiables registrados, se decide mantener estos valores como nulos.

### Valores Nulos Precio por km

In [133]:
df["Precio por km"].isna().sum()

np.int64(1034)

In [134]:
(df["Total Kms"] == 0).sum()

np.int64(850)

In [135]:
df[
    df["Precio por km"].isna()
][["NameResort", "Adult", "Total Kms"]].head(10)

                                           NameResort  Adult  Total Kms
6   Kaltenbach – Hochzillertal/Hochfügen (SKi-opti...   52.0       83.0
8   Schladming – Planai/​Hochwurzen/​Hauser Kaibli...   52.0      123.0
10                                 Silvretta Montafon   53.0      113.0
12                                         Obertauern   53.0      100.0
14             Hochkönig – Maria Alm/Dienten/Mühlbach   51.0      112.0
15  Snow Space Salzburg – Flachau/Wagrain/St. Joha...   52.0      115.0
20                                         Katschberg   43.0       70.0
22                   Ski Juwel Alpbachtal Wildschönau   52.0       93.1
25                    Großglockner Resort Kals-Matrei   43.0       37.0
30                             Großarltal/Dorfgastein   43.0       70.1

In [136]:
df[
    df["Precio por km"].isna()
]["Adult"].isna().sum()

np.int64(0)

In [137]:
df["Precio por km"] = (df["Adult"] / df["Total Kms"]).round(2)

df["Precio por km"] = df["Precio por km"].replace([np.inf, -np.inf], np.nan)

In [138]:
df["Precio por km"].isna().sum()

np.int64(850)

#### Los valores nulos de `Precio por km` corresponden a estaciones con `Total Kms = 0`, por lo que no es posible calcular el indicador.

In [139]:
nulos = pd.DataFrame({
    "Nulos": df.isnull().sum(),
    "Porcentaje (%)": round(df.isnull().mean() * 100, 2)
})

nulos = nulos[nulos["Nulos"] > 0].sort_values("Nulos", ascending=False)

nulos

                                                    Nulos  Porcentaje (%)
Snow reliability                                     5040           92.16
Access, on-site parking                              5040           92.16
Mountain restaurants, ski huts, gastronomy           5040           92.16
Environmentally friendly ski operation               5040           92.16
Cleanliness and hygiene                              5040           92.16
Orientation (trail map, information boards, sig...   5040           92.16
Snow parks                                           5040           92.16
Cross-country skiing and trails                      5040           92.16
Families and children                                5040           92.16
Beginners                                            5040           92.16
Après-ski                                            5040           92.16
Accommodation offering directly at the slopes a...   5040           92.16
Ski resort size                                      2017           36.88
Lifts and cable cars                                 2017           36.88
Slope offering, variety of runs                      2017           36.88
Rate                                                 2003           36.62
% Pistas intermedias                                  850           15.54
% Pistas fáciles                                      850           15.54
% Pistas difíciles                                    850           15.54
Precio por km                                         850           15.54
longitude                                              43            0.79
latitude                                               43            0.79

### Valores Nulos Rate

In [140]:
(
    df["Rate"].isna()
    ==
    df["Ski resort size"].isna()
).all()

np.False_

In [141]:
(
    df["Rate"].isna()
    ==
    df["Lifts and cable cars"].isna()
).all()

np.False_

In [142]:
(
    df["Rate"].isna()
    ==
    df["Slope offering, variety of runs"].isna()
).all()

np.False_

In [143]:
df[df["Rate"].isna()][
    ["NameResort", "Country", "Total Kms", "Adult", "Tamaño estación"]
].head(20)

,NameResort,Country,Total Kms,Adult,Tamaño estación
155,annerlbauerlifte-krieglach,Austria,0.5,0.0,Muy pequeña
156,arabichl-kirchberg-am-wechsel,Austria,2.0,16.0,Muy pequeña
161,astenlift-st-veit-im-pongau,Austria,0.7,0.0,Muy pequeña
162,bachrain-golling-an-der-salzach,Austria,0.5,0.0,Muy pequeña
166,bameshub-neukirchen-am-waldeeschenau,Austria,0.6,0.0,Muy pequeña
169,bernrad-natternbach,Austria,0.5,0.0,Muy pequeña
172,birkenlift,Austria,1.0,28.0,Muy pequeña
176,bonka-kirchbach-st-andrae-woerdern,Austria,0.2,0.0,Muy pequeña
178,brandlwiese-kaumberg,Austria,0.5,0.0,Muy pequeña
180,braz-innerbraz,Austria,0.5,41.0,Muy pequeña
185,bschlabs-pfafflar,Austria,1.0,0.0,Muy pequeña
193,druckerhof-unterach-am-attersee,Austria,1.0,0.0,Muy pequeña
200,eugendorf,Austria,1.0,17.0,Muy pequeña
203,feichtecklift-brandlucken-st-kathrein-am-offenegg,Austria,3.0,0.0,Muy pequeña
206,fellachlift-virgen,Austria,1.0,10.0,Muy pequeña
207,fischbach,Austria,1.2,0.0,Muy pequeña
209,foersterkogel-puchenstuben,Austria,0.5,20.0,Muy pequeña
211,frauenstaffl-ulrichsberg-waidhofen-an-der-thaya,Austria,0.8,0.0,Muy pequeña
212,freistadt,Austria,0.5,0.0,Muy pequeña
222,goellerlifts-gscheid-st-aegyd-am-neuwalde,Austria,4.0,23.0,Muy pequeña

In [144]:
df[df["Rate"].isna()][
    [
        "Rate",
        "Ski resort size",
        "Slope offering, variety of runs",
        "Lifts and cable cars"
    ]
].isna().sum()

Rate                               2003
Ski resort size                    2003
Slope offering, variety of runs    2003
Lifts and cable cars               2003
dtype: int64

In [145]:
df[
    (df["Rate"].isna()) &
    (
        df["Ski resort size"].notna() |
        df["Slope offering, variety of runs"].notna() |
        df["Lifts and cable cars"].notna()
    )
][
    ["NameResort", "Country", "Ski resort size",
     "Slope offering, variety of runs",
     "Lifts and cable cars"]
].head(20)

Empty DataFrame
Columns: [NameResort, Country, Ski resort size, Slope offering, variety of runs, Lifts and cable cars]
Index: []

#### La variable Rate presenta 2003 valores nulos. Tras analizar estos registros, se comprobó que las mismas estaciones también carecen de información en las variables Ski resort size, Slope offering, variety of runs y Lifts and cable cars. Esto indica que dichas estaciones no fueron evaluadas en la fuente original y, por tanto, no disponen de una valoración global. Al no existir información suficiente para estimar una puntuación de forma objetiva, se decide mantener los valores nulos.

### Valores Nulos Ski resort size, Lifts and cable cars, Slope offering, variety of runs

In [146]:
df[
    df["Ski resort size"].isna()
][["NameResort", "Country", "Total Kms", "Tamaño estación"]].head(20)

,NameResort,Country,Total Kms,Tamaño estación
155,annerlbauerlifte-krieglach,Austria,0.5,Muy pequeña
156,arabichl-kirchberg-am-wechsel,Austria,2.0,Muy pequeña
161,astenlift-st-veit-im-pongau,Austria,0.7,Muy pequeña
162,bachrain-golling-an-der-salzach,Austria,0.5,Muy pequeña
166,bameshub-neukirchen-am-waldeeschenau,Austria,0.6,Muy pequeña
169,bernrad-natternbach,Austria,0.5,Muy pequeña
172,birkenlift,Austria,1.0,Muy pequeña
176,bonka-kirchbach-st-andrae-woerdern,Austria,0.2,Muy pequeña
178,brandlwiese-kaumberg,Austria,0.5,Muy pequeña
180,braz-innerbraz,Austria,0.5,Muy pequeña
185,bschlabs-pfafflar,Austria,1.0,Muy pequeña
193,druckerhof-unterach-am-attersee,Austria,1.0,Muy pequeña
200,eugendorf,Austria,1.0,Muy pequeña
203,feichtecklift-brandlucken-st-kathrein-am-offenegg,Austria,3.0,Muy pequeña
206,fellachlift-virgen,Austria,1.0,Muy pequeña
207,fischbach,Austria,1.2,Muy pequeña
209,foersterkogel-puchenstuben,Austria,0.5,Muy pequeña
211,frauenstaffl-ulrichsberg-waidhofen-an-der-thaya,Austria,0.8,Muy pequeña
212,freistadt,Austria,0.5,Muy pequeña
222,goellerlifts-gscheid-st-aegyd-am-neuwalde,Austria,4.0,Muy pequeña

In [147]:
df[
    (df["Rate"].notna()) &
    (
        df["Ski resort size"].isna() |
        df["Lifts and cable cars"].isna() |
        df["Slope offering, variety of runs"].isna()
    )
][[
    "NameResort",
    "Country",
    "Rate",
    "Ski resort size",
    "Lifts and cable cars",
    "Slope offering, variety of runs"
]]

,NameResort,Country,Rate,Ski resort size,Lifts and cable cars,"Slope offering, variety of runs"
829,sangiacomocardini-monte-alpet,Italy,3.0,NaN,NaN,NaN
860,monte-verena-mezzaselva-di-roana,Italy,2.8,NaN,NaN,NaN
862,laceno-bagnoli-irpino,Italy,2.8,NaN,NaN,NaN
865,chiomonte-frais,Italy,2.8,NaN,NaN,NaN
1073,galibier-thabor-valmeiniervalloire,France,3.9,NaN,NaN,NaN
1315,Ounasvaara – Rovaniemi,Finland,3.3,NaN,NaN,NaN
1486,oppdal,Norway,3.3,NaN,NaN,NaN
1490,rauland-skisenterholtardalen,Norway,2.9,NaN,NaN,NaN
1495,uvdal-alpinsenter,Norway,2.8,NaN,NaN,NaN
1496,tjoerhomfjelletaalsheia-skisenter-sirdal,Norway,2.8,NaN,NaN,NaN
1595,Fjällby – Björkliden,Sweden,3.3,NaN,NaN,NaN
3295,straja,Romania,3.0,NaN,NaN,NaN
3297,predeal,Romania,2.8,NaN,NaN,NaN
3469,kolasportland,Northwest Russia,2.8,NaN,NaN,NaN

In [148]:
len(
    df[
        (df["Rate"].notna()) &
        (
            df["Ski resort size"].isna() |
            df["Lifts and cable cars"].isna() |
            df["Slope offering, variety of runs"].isna()
        )
    ]
)

14

### Variables de valoración específicas. Las variables `Ski resort size`, `Lifts and cable cars` y `Slope offering, variety of runs` presentan 2017 valores nulos.La mayoría de estos registros corresponden a estaciones que no fueron evaluadas en la fuente original y que tampoco disponen de una valoración global (`Rate`). Adicionalmente, se identificaron 14 estaciones con valoración general disponible pero sin desglose de puntuaciones específicas, lo que indica una inconsistencia en la información proporcionada por la fuente. Dado que se trata de valoraciones subjetivas y no existe información suficiente para estimarlas de forma fiable, se decide mantener los valores nulos.

### Valores nulos de columnas con un 92,16% de NaN

In [149]:
(
    df["Snow reliability"].isna()
    ==
    df["Access, on-site parking"].isna()
).all()

np.True_

In [150]:
(
    df["Snow reliability"].isna()
    ==
    df["Rate"].isna()
).all()

np.False_

In [151]:
df["Snow reliability"].notna().sum()

np.int64(429)

In [152]:
df["Rate"].notna().sum()

np.int64(3466)

#### Variables de valoración avanzada. Las variables relacionadas con valoraciones específicas de la experiencia en la estación (`Snow reliability`, `Après-ski`, `Families and children`, `Snow parks`, entre otras) presentan un elevado porcentaje de valores nulos (92,16 %). Tras su análisis se comprobó que estos nulos coinciden entre todas las variables del bloque, lo que indica que esta información únicamente está disponible para una muestra reducida de estaciones evaluadas por la fuente original. Dado que estas valoraciones pueden aportar valor en análisis específicos sobre calidad y experiencia del usuario, se decide conservar las columnas y mantener los valores nulos.

### Comprobación de duplicados

In [153]:
df.duplicated().sum()

np.int64(0)

In [154]:
df["NameResort"].duplicated().sum()

np.int64(0)

In [155]:
df.duplicated(subset=["NameResort", "Country"]).sum()

np.int64(0)

In [156]:
df.to_csv("ski_resorts_limpio.csv", index=False)

In [157]:
df = df.rename(columns={
    "NameResort": "Estación",
    "Continent": "Continente",
    "Country": "País",
    "State/Province": "Provincia/Estado",
    "Altitude": "Altitud",
    "Easy": "Km fáciles",
    "Intermediate": "Km intermedios",
    "Difficult": "Km difíciles",
    "Adult": "Precio forfait adulto",
    "Currency": "Moneda",
    "Rate": "Valoración",
    "Km Freeride": "Km freeride",
    "Ski resort size": "Tamaño del dominio esquiable",
    "Slope offering, variety of runs": "Variedad de pistas",
    "Lifts and cable cars": "Remontes y teleféricos",
    "Snow reliability": "Fiabilidad de nieve",
    "Access, on-site parking": "Acceso y aparcamiento",
    "Orientation (trail map, information boards, sign-postings)": "Señalización",
    "Cleanliness and hygiene": "Limpieza e higiene",
    "Environmentally friendly ski operation": "Sostenibilidad",
    "Mountain restaurants, ski huts, gastronomy": "Gastronomía",
    "Après-ski": "Après-ski",
    "Accommodation offering directly at the slopes and lifts": "Alojamiento en pistas",
    "Beginners": "Principiantes",
    "Snow parks": "Snowparks",
    "Cross-country skiing and trails": "Esquí de fondo",
    "Families and children": "Familias y niños",
    "latitude": "Latitud",
    "longitude": "Longitud",
    "Country Code": "Código país",
    "Total Kms": "Km totales",
    "Precio por km": "Precio por km",
    "Tamaño estación": "Categoría tamaño",
    "Perfil recomendado": "Perfil recomendado"
})

In [158]:
df_powerbi = df.copy()

In [159]:
df_powerbi.to_csv("ski_resorts_powerbi.csv", index=False)

In [160]:
df[df["Km totales"] > 1000][
    ["Estación", "País", "Km fáciles", "Km intermedios", "Km difíciles", "Km totales"]
].sort_values("Km totales", ascending=False).head(50)

Empty DataFrame
Columns: [Estación, País, Km fáciles, Km intermedios, Km difíciles, Km totales]
Index: []

In [161]:
df["Km totales"] = (
    df["Km fáciles"].fillna(0) +
    df["Km intermedios"].fillna(0) +
    df["Km difíciles"].fillna(0)
).round(2)

In [162]:
columnas_km = [
    "Km fáciles",
    "Km intermedios",
    "Km difíciles",
    "Km freeride",
    "Km totales"
]

df[columnas_km] = df[columnas_km].round(2)

In [164]:
df["Precio por km EUR"] = (
    df["Precio forfait adulto"] / df["Km totales"]
).round(2)

df["Precio por km EUR"] = df["Precio por km EUR"].replace([np.inf, -np.inf], np.nan)

In [165]:
df[df["Km totales"] > 1000][
    ["Estación", "País", "Km fáciles", "Km intermedios", "Km difíciles", "Km totales"]
]

Empty DataFrame
Columns: [Estación, País, Km fáciles, Km intermedios, Km difíciles, Km totales]
Index: []

In [166]:
import numpy as np

columnas_numericas = df.select_dtypes(include=np.number).columns

print(columnas_numericas.tolist())

['Valoración', 'Km freeride', 'Altitud', 'Km fáciles', 'Km intermedios', 'Km difíciles', 'Precio forfait adulto', 'Tamaño del dominio esquiable', 'Variedad de pistas', 'Remontes y teleféricos', 'Fiabilidad de nieve', 'Acceso y aparcamiento', 'Señalización', 'Limpieza e higiene', 'Sostenibilidad', 'Gastronomía', 'Après-ski', 'Alojamiento en pistas', 'Familias y niños', 'Principiantes', 'Snowparks', 'Esquí de fondo', 'Latitud', 'Longitud', 'Km totales', '% Pistas fáciles', '% Pistas intermedias', '% Pistas difíciles', 'Precio por km', 'Precio por km EUR']

In [167]:
df[columnas_numericas] = df[columnas_numericas].round(2)

In [168]:
for col in columnas_numericas:
    
    mask = (
        df[col].notna() &
        ((df[col] * 1000) % 1 != 0)
    )
    
    if mask.sum() > 0:
        print(f"{col}: {mask.sum()} valores")

Km intermedios: 2 valores
Latitud: 11 valores
% Pistas fáciles: 28 valores
% Pistas intermedias: 35 valores
% Pistas difíciles: 8 valores
Precio por km: 17 valores
Precio por km EUR: 17 valores

In [169]:
# Kilómetros
df["Km intermedios"] = df["Km intermedios"].round(2)

# Coordenadas
df["Latitud"] = df["Latitud"].round(4)

# Porcentajes
df["% Pistas fáciles"] = df["% Pistas fáciles"].round(2)
df["% Pistas intermedias"] = df["% Pistas intermedias"].round(2)
df["% Pistas difíciles"] = df["% Pistas difíciles"].round(2)

# Precios
df["Precio por km"] = df["Precio por km"].round(2)
df["Precio por km EUR"] = df["Precio por km EUR"].round(2)

In [170]:
for col in [
    "Km intermedios",
    "Latitud",
    "% Pistas fáciles",
    "% Pistas intermedias",
    "% Pistas difíciles",
    "Precio por km",
    "Precio por km EUR"
]:
    
    mask = (
        df[col].notna() &
        ((df[col] * 1000) % 1 != 0)
    )
    
    print(f"{col}: {mask.sum()} valores")

Km intermedios: 2 valores
Latitud: 11 valores
% Pistas fáciles: 28 valores
% Pistas intermedias: 35 valores
% Pistas difíciles: 8 valores
Precio por km: 17 valores
Precio por km EUR: 17 valores

In [171]:
df["Km totales"].max()

np.float64(600.0)

In [172]:
df.sort_values("Km totales", ascending=False)[
    ["Estación", "País", "Km totales"]
].head(20)

,Estación,País,Km totales
1057,Les 3 Vallées – Val Thorens/Les Menuires/Mérib...,France,600.0
443,Les Portes du Soleil – Morzine/Avoriaz/Les Get...,Switzerland,580.0
442,4 Vallées – Verbier/La Tzoumaz/Nendaz/Veysonna...,Switzerland,412.0
782,Via Lattea – Sestriere/Sauze d’Oulx/San Sicari...,Italy,400.0
436,Zermatt/Breuil-Cervinia/Valtournenche – Matter...,Switzerland,322.0
1070,Les Sybelles – Le Corbier/La Toussuire/Les Bot...,France,310.5
3,Ski Arlberg,Austria,305.0
1058,Tignes/Val d'Isère,France,300.0
2,SkiWelt Wilder Kaiser-Brixental,Austria,284.0
5,Saalbach Hinterglemm Leogang Fieberbrunn (Skic...,Austria,270.0
1066,Le Grand Massif – Flaine/Les Carroz/Morillon/S...,France,265.0
1064,Megève/Saint-Gervais,France,263.0
1059,Serre Chevalier – Briançon/Chantemerle/Villene...,France,250.5
3568,big-sky-resort,USA,250.0
1063,Alpe d'Huez,France,250.0
3845,park-city,USA,250.0
1,Ischgl/Samnaun – Silvretta Arena,Austria,238.0
3934,snowmass,USA,236.2
3999,vail,USA,234.0
433,Arosa Lenzerheide,Switzerland,225.0

In [175]:
for col in columnas_numericas:
    
    mask = (
        df[col].notna() &
        ((df[col] * 100) % 1 != 0)
    )

    print(f"{col}: {mask.sum()} valores")

Valoración: 622 valores
Km freeride: 5 valores
Altitud: 0 valores
Km fáciles: 118 valores
Km intermedios: 100 valores
Km difíciles: 44 valores
Precio forfait adulto: 0 valores
Tamaño del dominio esquiable: 646 valores
Variedad de pistas: 269 valores
Remontes y teleféricos: 92 valores
Fiabilidad de nieve: 0 valores
Acceso y aparcamiento: 0 valores
Señalización: 0 valores
Limpieza e higiene: 0 valores
Sostenibilidad: 0 valores
Gastronomía: 0 valores
Après-ski: 0 valores
Alojamiento en pistas: 0 valores
Familias y niños: 0 valores
Principiantes: 0 valores
Snowparks: 0 valores
Esquí de fondo: 0 valores
Latitud: 644 valores
Longitud: 413 valores
Km totales: 166 valores
% Pistas fáciles: 156 valores
% Pistas intermedias: 150 valores
% Pistas difíciles: 188 valores
Precio por km: 230 valores
Precio por km EUR: 230 valores

In [176]:
columnas_numericas = df.select_dtypes(include="number").columns

df[columnas_numericas] = df[columnas_numericas].round(2)

In [177]:
for col in columnas_numericas:
    
    mask = (
        df[col].notna() &
        ((df[col] * 100) % 1 != 0)
    )

    print(f"{col}: {mask.sum()} valores")

Valoración: 622 valores
Km freeride: 5 valores
Altitud: 0 valores
Km fáciles: 118 valores
Km intermedios: 100 valores
Km difíciles: 44 valores
Precio forfait adulto: 0 valores
Tamaño del dominio esquiable: 646 valores
Variedad de pistas: 269 valores
Remontes y teleféricos: 92 valores
Fiabilidad de nieve: 0 valores
Acceso y aparcamiento: 0 valores
Señalización: 0 valores
Limpieza e higiene: 0 valores
Sostenibilidad: 0 valores
Gastronomía: 0 valores
Après-ski: 0 valores
Alojamiento en pistas: 0 valores
Familias y niños: 0 valores
Principiantes: 0 valores
Snowparks: 0 valores
Esquí de fondo: 0 valores
Latitud: 644 valores
Longitud: 413 valores
Km totales: 166 valores
% Pistas fáciles: 156 valores
% Pistas intermedias: 150 valores
% Pistas difíciles: 188 valores
Precio por km: 230 valores
Precio por km EUR: 230 valores

In [178]:
# Redondear TODAS las columnas numéricas a 2 decimales
columnas_numericas = df.select_dtypes(include='number').columns

for col in columnas_numericas:
    df[col] = df[col].round(2)

In [179]:
df.loc[df["Valoración"] * 100 % 1 != 0, "Valoración"].head(20)

0      4.9
10     4.6
11     4.6
16     4.4
17     4.4
18     4.4
19     4.4
28     4.1
29     4.1
30     4.1
31     4.1
151    2.3
155    NaN
156    NaN
157    1.1
159    1.1
161    NaN
162    NaN
163    1.1
165    1.1
Name: Valoración, dtype: float64

In [180]:
for col in columnas_numericas:

    mask = (
        df[col].notna() &
        (abs(df[col] - df[col].round(2)) > 1e-9)
    )

    print(f"{col}: {mask.sum()} valores")

Valoración: 0 valores
Km freeride: 0 valores
Altitud: 0 valores
Km fáciles: 0 valores
Km intermedios: 0 valores
Km difíciles: 0 valores
Precio forfait adulto: 0 valores
Tamaño del dominio esquiable: 0 valores
Variedad de pistas: 0 valores
Remontes y teleféricos: 0 valores
Fiabilidad de nieve: 0 valores
Acceso y aparcamiento: 0 valores
Señalización: 0 valores
Limpieza e higiene: 0 valores
Sostenibilidad: 0 valores
Gastronomía: 0 valores
Après-ski: 0 valores
Alojamiento en pistas: 0 valores
Familias y niños: 0 valores
Principiantes: 0 valores
Snowparks: 0 valores
Esquí de fondo: 0 valores
Latitud: 0 valores
Longitud: 0 valores
Km totales: 0 valores
% Pistas fáciles: 0 valores
% Pistas intermedias: 0 valores
% Pistas difíciles: 0 valores
Precio por km: 0 valores
Precio por km EUR: 0 valores

In [181]:
df.to_csv(
    "ski_resorts_powerbi.csv",
    index=False,
    float_format="%.2f"
)

In [182]:
df.loc[df["Valoración"] * 100 % 1 != 0, "Valoración"].head(10)

0     4.9
10    4.6
11    4.6
16    4.4
17    4.4
18    4.4
19    4.4
28    4.1
29    4.1
30    4.1
Name: Valoración, dtype: float64

## Resumen del preprocesamiento

Durante esta fase se realizaron las siguientes tareas de limpieza y transformación de datos:

- Revisión de la estructura, tipos de datos y calidad inicial del dataset.
- Eliminación de registros completamente vacíos.
- Revisión y tratamiento de valores nulos.
- Corrección y estandarización de la variable `Currency`.
- Completar valores faltantes de moneda utilizando la información disponible por país.
- Eliminación de la columna `Stars` debido a su elevado porcentaje de valores nulos y escasa utilidad analítica.
- Creación de la variable `Total Kms` a partir de la suma de kilómetros fáciles, intermedios y difíciles.
- Validación de la coherencia entre los kilómetros calculados y los valores originales.
- Completar valores nulos de `Km Freeride` con valor 0.
- Tratamiento de valores faltantes en la variable `Adult`.
- Completar valores faltantes en `Country Code`.
- Tratamiento de valores faltantes en las coordenadas geográficas (`latitude` y `longitude`) para facilitar su representación en mapas.
- Creación de la variable `Precio por km`.
- Creación de la variable `Tamaño estación`.
- Creación de las variables `% Pistas fáciles`, `% Pistas intermedias` y `% Pistas difíciles`.
- Creación de la variable `Perfil recomendado`.
- Análisis y documentación de los valores nulos restantes para determinar si debían mantenerse o ser tratados.
- Verificación de la inexistencia de registros duplicados.
- Exportación del dataset limpio para su posterior análisis en Power BI.

Como resultado, se obtuvo un conjunto de datos preparado para la fase de análisis exploratorio (EDA) y construcción del dashboard.