## Preprocesamiento de datos

#### En esta fase se realizará la limpieza y preparación del conjunto de datos para garantizar su calidad antes del análisis. Se revisarán los valores nulos, los tipos de datos y aquellas variables que puedan afectar al análisis o al posterior desarrollo del dashboard en Power BI.

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

#### Cargamos de nuevo el dataset original para trabajar siempre desde los datos en bruto y aplicar las transformaciones de limpieza en este notebook.

In [3]:
df = pd.read_csv("../data/raw/resortworldwide.csv")
df.head(2)

,URL,Rate,NameResort,Stars,Km Freeride,Continent,Country,State/Province,Altitude,Easy,Intermediate,Difficult,Adult,Currency,Ski resort size,"Slope offering, variety of runs",Lifts and cable cars,Snow reliability,"Access, on-site parking","Orientation (trail map, information boards, sign-postings)",Cleanliness and hygiene,Environmentally friendly ski operation,"Mountain restaurants, ski huts, gastronomy",Après-ski,Accommodation offering directly at the slopes and lifts,Families and children,Beginners,Snow parks,Cross-country skiing and trails,country,latitude,longitude,Total Kms
0,http://www.skiresort.info/ski-resort/kitzski-k...,4.9,KitzSki – Kitzbühel/Kirchberg,5.0,45.0,Europe,Austria,Tyrol (Tirol),2000.0,101.0,61.0,17.0,55,European Euro,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","4,0","5,0","5,0","5,0","5,0","5,0",AT,47.516231,14.550072,179
1,http://www.skiresort.info/ski-resort/ischglsam...,4.8,Ischgl/Samnaun – Silvretta Arena,5.0,15.0,Europe,Austria,Tyrol (Tirol),2872.0,47.0,142.0,49.0,53,European Euro,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","5,0","5,0","4,0","4,0","5,0","4,0",AT,47.516231,14.550072,238

In [4]:
df.shape

(5478, 33)

## Valores Nulos

#### Antes de aplicar cualquier transformación, analizamos la cantidad y el porcentaje de valores nulos de cada variable. Esta información nos permitirá decidir qué columnas conservar, tratar o eliminar durante el proceso de limpieza.

In [5]:
nulls = pd.DataFrame({
    "Nulos": df.isnull().sum(),
    "Porcentaje (%)": round(df.isnull().mean() * 100, 2)
}).sort_values(by="Porcentaje (%)", ascending=False)

nulls

                                                    Nulos  Porcentaje (%)
Stars                                                5065           92.46
Accommodation offering directly at the slopes a...   5049           92.17
Après-ski                                            5049           92.17
Mountain restaurants, ski huts, gastronomy           5049           92.17
Environmentally friendly ski operation               5049           92.17
Cross-country skiing and trails                      5049           92.17
Snow parks                                           5049           92.17
Beginners                                            5049           92.17
Families and children                                5049           92.17
Cleanliness and hygiene                              5049           92.17
Orientation (trail map, information boards, sig...   5049           92.17
Access, on-site parking                              5049           92.17
Snow reliability                                     5049           92.17
Km Freeride                                          4998           91.24
Ski resort size                                      2026           36.98
Lifts and cable cars                                 2026           36.98
Slope offering, variety of runs                      2026           36.98
Rate                                                 2007           36.64
country                                               599           10.93
longitude                                             598           10.92
latitude                                              598           10.92
Adult                                                   9            0.16
State/Province                                          9            0.16
Continent                                               9            0.16
Currency                                                9            0.16
Altitude                                                9            0.16
Country                                                 9            0.16
URL                                                     0            0.00
NameResort                                              0            0.00
Intermediate                                            0            0.00
Easy                                                    0            0.00
Difficult                                               0            0.00
Total Kms                                               0            0.00

In [6]:
nulls[nulls["Nulos"] > 0]

                                                    Nulos  Porcentaje (%)
Stars                                                5065           92.46
Accommodation offering directly at the slopes a...   5049           92.17
Après-ski                                            5049           92.17
Mountain restaurants, ski huts, gastronomy           5049           92.17
Environmentally friendly ski operation               5049           92.17
Cross-country skiing and trails                      5049           92.17
Snow parks                                           5049           92.17
Beginners                                            5049           92.17
Families and children                                5049           92.17
Cleanliness and hygiene                              5049           92.17
Orientation (trail map, information boards, sig...   5049           92.17
Access, on-site parking                              5049           92.17
Snow reliability                                     5049           92.17
Km Freeride                                          4998           91.24
Ski resort size                                      2026           36.98
Lifts and cable cars                                 2026           36.98
Slope offering, variety of runs                      2026           36.98
Rate                                                 2007           36.64
country                                               599           10.93
longitude                                             598           10.92
latitude                                              598           10.92
Adult                                                   9            0.16
State/Province                                          9            0.16
Continent                                               9            0.16
Currency                                                9            0.16
Altitude                                                9            0.16
Country                                                 9            0.16

In [9]:
columnas_revision = [
    "Stars",
    "Rate",
    "Ski resort size",
    "Slope offering, variety of runs",
    "Lifts and cable cars",
    "Snow reliability",
    "Access, on-site parking",
    "Orientation (trail map, information boards, sign-postings)",
    "Cleanliness and hygiene",
    "Environmentally friendly ski operation",
    "Mountain restaurants, ski huts, gastronomy",
    "Après-ski",
    "Accommodation offering directly at the slopes and lifts",
    "Beginners",
    "Snow parks",
    "Cross-country skiing and trails",
    "Families and children",
    "Km Freeride"
]

In [10]:
df[columnas_revision].head(10)

KeyError: "['Ski resort size', 'Slope offering, variety of runs', 'Lifts and cable cars', 'Snow reliability', 'Access, on-site parking', 'Orientation (trail map, information boards, sign-postings)', 'Cleanliness and hygiene', 'Environmentally friendly ski operation', 'Mountain restaurants, ski huts, gastronomy', 'Après-ski', 'Accommodation offering directly at the slopes and lifts', 'Beginners', 'Snow parks', 'Cross-country skiing and trails', 'Families and children'] not in index"

In [11]:
df.columns.tolist()

['URL',
 'Rate',
 'NameResort',
 'Stars',
 'Km Freeride',
 'Continent',
 'Country',
 'State/Province',
 'Altitude',
 'Easy',
 'Intermediate ',
 'Difficult',
 'Adult',
 'Currency',
 'Ski resort size ',
 'Slope offering, variety of runs ',
 'Lifts and cable cars ',
 'Snow reliability ',
 'Access, on-site parking ',
 'Orientation (trail map, information boards, sign-postings) ',
 'Cleanliness and hygiene ',
 'Environmentally friendly ski operation ',
 'Mountain restaurants, ski huts, gastronomy ',
 'Après-ski ',
 'Accommodation offering directly at the slopes and lifts ',
 'Families and children ',
 'Beginners ',
 'Snow parks ',
 'Cross-country skiing and trails ',
 'country',
 'latitude',
 'longitude',
 'Total Kms']

In [12]:
for col in df.columns:
    print(repr(col))

'URL'
'Rate'
'NameResort'
'Stars'
'Km Freeride'
'Continent'
'Country'
'State/Province'
'Altitude'
'Easy'
'Intermediate '
'Difficult'
'Adult'
'Currency'
'Ski resort size '
'Slope offering, variety of runs '
'Lifts and cable cars '
'Snow reliability '
'Access, on-site parking '
'Orientation (trail map, information boards, sign-postings) '
'Cleanliness and hygiene '
'Environmentally friendly ski operation '
'Mountain restaurants, ski huts, gastronomy '
'Après-ski '
'Accommodation offering directly at the slopes and lifts '
'Families and children '
'Beginners '
'Snow parks '
'Cross-country skiing and trails '
'country'
'latitude'
'longitude'
'Total Kms'

#### Se eliminan los espacios en blanco al inicio y al final de los nombres de las columnas para evitar errores durante el tratamiento y análisis del dataset.

In [13]:
df.columns = df.columns.str.strip()

In [14]:
for col in df.columns:
    print(repr(col))

'URL'
'Rate'
'NameResort'
'Stars'
'Km Freeride'
'Continent'
'Country'
'State/Province'
'Altitude'
'Easy'
'Intermediate'
'Difficult'
'Adult'
'Currency'
'Ski resort size'
'Slope offering, variety of runs'
'Lifts and cable cars'
'Snow reliability'
'Access, on-site parking'
'Orientation (trail map, information boards, sign-postings)'
'Cleanliness and hygiene'
'Environmentally friendly ski operation'
'Mountain restaurants, ski huts, gastronomy'
'Après-ski'
'Accommodation offering directly at the slopes and lifts'
'Families and children'
'Beginners'
'Snow parks'
'Cross-country skiing and trails'
'country'
'latitude'
'longitude'
'Total Kms'

In [15]:
df[columnas_revision].head(10)

,Stars,Rate,Ski resort size,"Slope offering, variety of runs",Lifts and cable cars,Snow reliability,"Access, on-site parking","Orientation (trail map, information boards, sign-postings)",Cleanliness and hygiene,Environmentally friendly ski operation,"Mountain restaurants, ski huts, gastronomy",Après-ski,Accommodation offering directly at the slopes and lifts,Beginners,Snow parks,Cross-country skiing and trails,Families and children,Km Freeride
0,5.0,4.9,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","4,0","5,0","5,0","5,0","5,0","5,0",45.0
1,5.0,4.8,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","5,0","5,0","4,0","5,0","4,0","4,0",15.0
2,5.0,4.8,"5,0",5.0,"5,0",4.0,"5,0","4,0","5,0","5,0","5,0","4,0","4,0","5,0","5,0","5,0","5,0",26.0
3,5.0,4.8,"5,0",5.0,"5,0",5.0,"4,0","4,0","4,0","4,0","5,0","5,0","5,0","5,0","4,0","4,0","5,0",200.0
4,5.0,4.8,"5,0",5.0,"5,0",5.0,"4,0","5,0","4,0","4,0","5,0","4,0","4,0","4,0","5,0","4,0","5,0",28.0
5,5.0,4.7,"5,0",5.0,"5,0",4.0,"3,0","5,0","5,0","4,0","5,0","5,0","5,0","5,0","5,0","4,0","5,0",0.0
6,5.0,4.7,"4,0",5.0,"5,0",5.0,"5,0","5,0","5,0","4,0","5,0","4,0","5,0","5,0","4,0","3,0","5,0",3.6
7,5.0,4.7,"5,0",5.0,"5,0",5.0,"4,0","4,0","5,0","4,0","5,0","4,0","5,0","4,0","5,0","4,0","5,0",3.0
8,4.0,4.7,"5,0",5.0,"5,0",5.0,"4,0","4,0","5,0","4,0","5,0","5,0","5,0","3,0","5,0","4,0","5,0",4.0
9,5.0,4.7,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","5,0","5,0","4,0","4,0","3,0","4,0",0.0

In [16]:
df[df["Snow parks"].isna()].head()

,URL,Rate,NameResort,Stars,Km Freeride,Continent,Country,State/Province,Altitude,Easy,Intermediate,Difficult,Adult,Currency,Ski resort size,"Slope offering, variety of runs",Lifts and cable cars,Snow reliability,"Access, on-site parking","Orientation (trail map, information boards, sign-postings)",Cleanliness and hygiene,Environmentally friendly ski operation,"Mountain restaurants, ski huts, gastronomy",Après-ski,Accommodation offering directly at the slopes and lifts,Families and children,Beginners,Snow parks,Cross-country skiing and trails,country,latitude,longitude,Total Kms
59,http://www.skiresort.info/ski-resort/filzmoos/,3.7,. Filzmoos,2.0,0.0,Europe,Austria,Salzburg (Salzburger Land),1645.0,6.0,6.0,1.0,43,European Euro,"2,3",2.5,"3,4",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AT,47.516231,14.550072,13
75,http://www.skiresort.info/ski-resort/hochficht/,3.6,. Hochficht,2.0,3.0,Europe,Austria,Upper Austria (Oberosterreich),1338.0,9.0,10.0,1.0,39,European Euro,"2,4",2.6,"3,5",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AT,47.516231,14.550072,20
76,http://www.skiresort.info/ski-resort/patscherk...,3.6,. Patscherkofel – Innsbruck-Igls,3.0,0.0,Europe,Austria,Tyrol (Tirol),1969.0,5.0,9.0,4.0,37,European Euro,"2,4",2.7,"4,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AT,47.516231,14.550072,18
77,http://www.skiresort.info/ski-resort/moenichki...,3.6,. Mönichkirchen/Mariensee,2.0,0.0,Europe,Austria,Lower Austria (Niederosterreich),1450.0,5.5,6.0,2.0,"35,50",European Euro,"2,3",2.6,"3,9",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AT,47.516231,14.550072,13
78,http://www.skiresort.info/ski-resort/sportgast...,3.6,Sportgastein,5.0,7.7,Europe,Austria,Salzburg (Salzburger Land),2686.0,3.5,13.2,1.5,52,European Euro,"2,5",2.7,"4,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AT,47.516231,14.550072,18

In [17]:
df[df["Snow parks"].notna()].head()

,URL,Rate,NameResort,Stars,Km Freeride,Continent,Country,State/Province,Altitude,Easy,Intermediate,Difficult,Adult,Currency,Ski resort size,"Slope offering, variety of runs",Lifts and cable cars,Snow reliability,"Access, on-site parking","Orientation (trail map, information boards, sign-postings)",Cleanliness and hygiene,Environmentally friendly ski operation,"Mountain restaurants, ski huts, gastronomy",Après-ski,Accommodation offering directly at the slopes and lifts,Families and children,Beginners,Snow parks,Cross-country skiing and trails,country,latitude,longitude,Total Kms
0,http://www.skiresort.info/ski-resort/kitzski-k...,4.9,KitzSki – Kitzbühel/Kirchberg,5.0,45.0,Europe,Austria,Tyrol (Tirol),2000.0,101.0,61.0,17.0,55,European Euro,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","4,0","5,0","5,0","5,0","5,0","5,0",AT,47.516231,14.550072,179
1,http://www.skiresort.info/ski-resort/ischglsam...,4.8,Ischgl/Samnaun – Silvretta Arena,5.0,15.0,Europe,Austria,Tyrol (Tirol),2872.0,47.0,142.0,49.0,53,European Euro,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","5,0","5,0","4,0","4,0","5,0","4,0",AT,47.516231,14.550072,238
2,http://www.skiresort.info/ski-resort/skiwelt-w...,4.8,SkiWelt Wilder Kaiser-Brixental,5.0,26.0,Europe,Austria,Tyrol (Tirol),1957.0,122.0,129.0,33.0,49,European Euro,"5,0",5.0,"5,0",4.0,"5,0","4,0","5,0","5,0","5,0","4,0","4,0","5,0","5,0","5,0","5,0",AT,47.516231,14.550072,284
3,http://www.skiresort.info/ski-resort/st-antons...,4.8,Ski Arlberg,5.0,200.0,Europe,Austria,Tyrol (Tirol),2811.0,132.0,123.0,50.0,53,European Euro,"5,0",5.0,"5,0",5.0,"4,0","4,0","4,0","4,0","5,0","5,0","5,0","5,0","5,0","4,0","4,0",AT,47.516231,14.550072,305
4,http://www.skiresort.info/ski-resort/serfaus-f...,4.8,Serfaus-Fiss-Ladis,5.0,28.0,Europe,Austria,Tyrol (Tirol),2820.0,47.0,123.0,28.0,51,European Euro,"5,0",5.0,"5,0",5.0,"4,0","5,0","4,0","4,0","5,0","4,0","4,0","5,0","4,0","5,0","4,0",AT,47.516231,14.550072,198