## Preprocesamiento de datos

#### En esta fase se realizará la limpieza y preparación del conjunto de datos para garantizar su calidad antes del análisis. Se revisarán los valores nulos, los tipos de datos y aquellas variables que puedan afectar al análisis o al posterior desarrollo del dashboard en Power BI.

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

#### Cargamos de nuevo el dataset original para trabajar siempre desde los datos en bruto y aplicar las transformaciones de limpieza en este notebook.

In [3]:
df = pd.read_csv("../data/raw/resortworldwide.csv")
df.head(2)

,URL,Rate,NameResort,Stars,Km Freeride,Continent,Country,State/Province,Altitude,Easy,Intermediate,Difficult,Adult,Currency,Ski resort size,"Slope offering, variety of runs",Lifts and cable cars,Snow reliability,"Access, on-site parking","Orientation (trail map, information boards, sign-postings)",Cleanliness and hygiene,Environmentally friendly ski operation,"Mountain restaurants, ski huts, gastronomy",Après-ski,Accommodation offering directly at the slopes and lifts,Families and children,Beginners,Snow parks,Cross-country skiing and trails,country,latitude,longitude,Total Kms
0,http://www.skiresort.info/ski-resort/kitzski-k...,4.9,KitzSki – Kitzbühel/Kirchberg,5.0,45.0,Europe,Austria,Tyrol (Tirol),2000.0,101.0,61.0,17.0,55,European Euro,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","4,0","5,0","5,0","5,0","5,0","5,0",AT,47.516231,14.550072,179
1,http://www.skiresort.info/ski-resort/ischglsam...,4.8,Ischgl/Samnaun – Silvretta Arena,5.0,15.0,Europe,Austria,Tyrol (Tirol),2872.0,47.0,142.0,49.0,53,European Euro,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","5,0","5,0","4,0","4,0","5,0","4,0",AT,47.516231,14.550072,238

In [4]:
df.shape

(5478, 33)

## Valores Nulos

#### Antes de aplicar cualquier transformación, analizamos la cantidad y el porcentaje de valores nulos de cada variable. Esta información nos permitirá decidir qué columnas conservar, tratar o eliminar durante el proceso de limpieza.

In [5]:
nulls = pd.DataFrame({
    "Nulos": df.isnull().sum(),
    "Porcentaje (%)": round(df.isnull().mean() * 100, 2)
}).sort_values(by="Porcentaje (%)", ascending=False)

nulls

                                                    Nulos  Porcentaje (%)
Stars                                                5065           92.46
Accommodation offering directly at the slopes a...   5049           92.17
Après-ski                                            5049           92.17
Mountain restaurants, ski huts, gastronomy           5049           92.17
Environmentally friendly ski operation               5049           92.17
Cross-country skiing and trails                      5049           92.17
Snow parks                                           5049           92.17
Beginners                                            5049           92.17
Families and children                                5049           92.17
Cleanliness and hygiene                              5049           92.17
Orientation (trail map, information boards, sig...   5049           92.17
Access, on-site parking                              5049           92.17
Snow reliability                                     5049           92.17
Km Freeride                                          4998           91.24
Ski resort size                                      2026           36.98
Lifts and cable cars                                 2026           36.98
Slope offering, variety of runs                      2026           36.98
Rate                                                 2007           36.64
country                                               599           10.93
longitude                                             598           10.92
latitude                                              598           10.92
Adult                                                   9            0.16
State/Province                                          9            0.16
Continent                                               9            0.16
Currency                                                9            0.16
Altitude                                                9            0.16
Country                                                 9            0.16
URL                                                     0            0.00
NameResort                                              0            0.00
Intermediate                                            0            0.00
Easy                                                    0            0.00
Difficult                                               0            0.00
Total Kms                                               0            0.00

In [6]:
nulls[nulls["Nulos"] > 0]

                                                    Nulos  Porcentaje (%)
Stars                                                5065           92.46
Accommodation offering directly at the slopes a...   5049           92.17
Après-ski                                            5049           92.17
Mountain restaurants, ski huts, gastronomy           5049           92.17
Environmentally friendly ski operation               5049           92.17
Cross-country skiing and trails                      5049           92.17
Snow parks                                           5049           92.17
Beginners                                            5049           92.17
Families and children                                5049           92.17
Cleanliness and hygiene                              5049           92.17
Orientation (trail map, information boards, sig...   5049           92.17
Access, on-site parking                              5049           92.17
Snow reliability                                     5049           92.17
Km Freeride                                          4998           91.24
Ski resort size                                      2026           36.98
Lifts and cable cars                                 2026           36.98
Slope offering, variety of runs                      2026           36.98
Rate                                                 2007           36.64
country                                               599           10.93
longitude                                             598           10.92
latitude                                              598           10.92
Adult                                                   9            0.16
State/Province                                          9            0.16
Continent                                               9            0.16
Currency                                                9            0.16
Altitude                                                9            0.16
Country                                                 9            0.16

In [9]:
columnas_revision = [
    "Stars",
    "Rate",
    "Ski resort size",
    "Slope offering, variety of runs",
    "Lifts and cable cars",
    "Snow reliability",
    "Access, on-site parking",
    "Orientation (trail map, information boards, sign-postings)",
    "Cleanliness and hygiene",
    "Environmentally friendly ski operation",
    "Mountain restaurants, ski huts, gastronomy",
    "Après-ski",
    "Accommodation offering directly at the slopes and lifts",
    "Beginners",
    "Snow parks",
    "Cross-country skiing and trails",
    "Families and children",
    "Km Freeride"
]

In [10]:
df[columnas_revision].head(10)

KeyError: "['Ski resort size', 'Slope offering, variety of runs', 'Lifts and cable cars', 'Snow reliability', 'Access, on-site parking', 'Orientation (trail map, information boards, sign-postings)', 'Cleanliness and hygiene', 'Environmentally friendly ski operation', 'Mountain restaurants, ski huts, gastronomy', 'Après-ski', 'Accommodation offering directly at the slopes and lifts', 'Beginners', 'Snow parks', 'Cross-country skiing and trails', 'Families and children'] not in index"

In [11]:
df.columns.tolist()

['URL',
 'Rate',
 'NameResort',
 'Stars',
 'Km Freeride',
 'Continent',
 'Country',
 'State/Province',
 'Altitude',
 'Easy',
 'Intermediate ',
 'Difficult',
 'Adult',
 'Currency',
 'Ski resort size ',
 'Slope offering, variety of runs ',
 'Lifts and cable cars ',
 'Snow reliability ',
 'Access, on-site parking ',
 'Orientation (trail map, information boards, sign-postings) ',
 'Cleanliness and hygiene ',
 'Environmentally friendly ski operation ',
 'Mountain restaurants, ski huts, gastronomy ',
 'Après-ski ',
 'Accommodation offering directly at the slopes and lifts ',
 'Families and children ',
 'Beginners ',
 'Snow parks ',
 'Cross-country skiing and trails ',
 'country',
 'latitude',
 'longitude',
 'Total Kms']

In [12]:
for col in df.columns:
    print(repr(col))

'URL'
'Rate'
'NameResort'
'Stars'
'Km Freeride'
'Continent'
'Country'
'State/Province'
'Altitude'
'Easy'
'Intermediate '
'Difficult'
'Adult'
'Currency'
'Ski resort size '
'Slope offering, variety of runs '
'Lifts and cable cars '
'Snow reliability '
'Access, on-site parking '
'Orientation (trail map, information boards, sign-postings) '
'Cleanliness and hygiene '
'Environmentally friendly ski operation '
'Mountain restaurants, ski huts, gastronomy '
'Après-ski '
'Accommodation offering directly at the slopes and lifts '
'Families and children '
'Beginners '
'Snow parks '
'Cross-country skiing and trails '
'country'
'latitude'
'longitude'
'Total Kms'

#### Se eliminan los espacios en blanco al inicio y al final de los nombres de las columnas para evitar errores durante el tratamiento y análisis del dataset.

In [13]:
df.columns = df.columns.str.strip()

In [14]:
for col in df.columns:
    print(repr(col))

'URL'
'Rate'
'NameResort'
'Stars'
'Km Freeride'
'Continent'
'Country'
'State/Province'
'Altitude'
'Easy'
'Intermediate'
'Difficult'
'Adult'
'Currency'
'Ski resort size'
'Slope offering, variety of runs'
'Lifts and cable cars'
'Snow reliability'
'Access, on-site parking'
'Orientation (trail map, information boards, sign-postings)'
'Cleanliness and hygiene'
'Environmentally friendly ski operation'
'Mountain restaurants, ski huts, gastronomy'
'Après-ski'
'Accommodation offering directly at the slopes and lifts'
'Families and children'
'Beginners'
'Snow parks'
'Cross-country skiing and trails'
'country'
'latitude'
'longitude'
'Total Kms'

In [15]:
df[columnas_revision].head(10)

,Stars,Rate,Ski resort size,"Slope offering, variety of runs",Lifts and cable cars,Snow reliability,"Access, on-site parking","Orientation (trail map, information boards, sign-postings)",Cleanliness and hygiene,Environmentally friendly ski operation,"Mountain restaurants, ski huts, gastronomy",Après-ski,Accommodation offering directly at the slopes and lifts,Beginners,Snow parks,Cross-country skiing and trails,Families and children,Km Freeride
0,5.0,4.9,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","4,0","5,0","5,0","5,0","5,0","5,0",45.0
1,5.0,4.8,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","5,0","5,0","4,0","5,0","4,0","4,0",15.0
2,5.0,4.8,"5,0",5.0,"5,0",4.0,"5,0","4,0","5,0","5,0","5,0","4,0","4,0","5,0","5,0","5,0","5,0",26.0
3,5.0,4.8,"5,0",5.0,"5,0",5.0,"4,0","4,0","4,0","4,0","5,0","5,0","5,0","5,0","4,0","4,0","5,0",200.0
4,5.0,4.8,"5,0",5.0,"5,0",5.0,"4,0","5,0","4,0","4,0","5,0","4,0","4,0","4,0","5,0","4,0","5,0",28.0
5,5.0,4.7,"5,0",5.0,"5,0",4.0,"3,0","5,0","5,0","4,0","5,0","5,0","5,0","5,0","5,0","4,0","5,0",0.0
6,5.0,4.7,"4,0",5.0,"5,0",5.0,"5,0","5,0","5,0","4,0","5,0","4,0","5,0","5,0","4,0","3,0","5,0",3.6
7,5.0,4.7,"5,0",5.0,"5,0",5.0,"4,0","4,0","5,0","4,0","5,0","4,0","5,0","4,0","5,0","4,0","5,0",3.0
8,4.0,4.7,"5,0",5.0,"5,0",5.0,"4,0","4,0","5,0","4,0","5,0","5,0","5,0","3,0","5,0","4,0","5,0",4.0
9,5.0,4.7,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","5,0","5,0","4,0","4,0","3,0","4,0",0.0

In [16]:
df[df["Snow parks"].isna()].head()

,URL,Rate,NameResort,Stars,Km Freeride,Continent,Country,State/Province,Altitude,Easy,Intermediate,Difficult,Adult,Currency,Ski resort size,"Slope offering, variety of runs",Lifts and cable cars,Snow reliability,"Access, on-site parking","Orientation (trail map, information boards, sign-postings)",Cleanliness and hygiene,Environmentally friendly ski operation,"Mountain restaurants, ski huts, gastronomy",Après-ski,Accommodation offering directly at the slopes and lifts,Families and children,Beginners,Snow parks,Cross-country skiing and trails,country,latitude,longitude,Total Kms
59,http://www.skiresort.info/ski-resort/filzmoos/,3.7,. Filzmoos,2.0,0.0,Europe,Austria,Salzburg (Salzburger Land),1645.0,6.0,6.0,1.0,43,European Euro,"2,3",2.5,"3,4",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AT,47.516231,14.550072,13
75,http://www.skiresort.info/ski-resort/hochficht/,3.6,. Hochficht,2.0,3.0,Europe,Austria,Upper Austria (Oberosterreich),1338.0,9.0,10.0,1.0,39,European Euro,"2,4",2.6,"3,5",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AT,47.516231,14.550072,20
76,http://www.skiresort.info/ski-resort/patscherk...,3.6,. Patscherkofel – Innsbruck-Igls,3.0,0.0,Europe,Austria,Tyrol (Tirol),1969.0,5.0,9.0,4.0,37,European Euro,"2,4",2.7,"4,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AT,47.516231,14.550072,18
77,http://www.skiresort.info/ski-resort/moenichki...,3.6,. Mönichkirchen/Mariensee,2.0,0.0,Europe,Austria,Lower Austria (Niederosterreich),1450.0,5.5,6.0,2.0,"35,50",European Euro,"2,3",2.6,"3,9",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AT,47.516231,14.550072,13
78,http://www.skiresort.info/ski-resort/sportgast...,3.6,Sportgastein,5.0,7.7,Europe,Austria,Salzburg (Salzburger Land),2686.0,3.5,13.2,1.5,52,European Euro,"2,5",2.7,"4,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AT,47.516231,14.550072,18

In [17]:
df[df["Snow parks"].notna()].head()

,URL,Rate,NameResort,Stars,Km Freeride,Continent,Country,State/Province,Altitude,Easy,Intermediate,Difficult,Adult,Currency,Ski resort size,"Slope offering, variety of runs",Lifts and cable cars,Snow reliability,"Access, on-site parking","Orientation (trail map, information boards, sign-postings)",Cleanliness and hygiene,Environmentally friendly ski operation,"Mountain restaurants, ski huts, gastronomy",Après-ski,Accommodation offering directly at the slopes and lifts,Families and children,Beginners,Snow parks,Cross-country skiing and trails,country,latitude,longitude,Total Kms
0,http://www.skiresort.info/ski-resort/kitzski-k...,4.9,KitzSki – Kitzbühel/Kirchberg,5.0,45.0,Europe,Austria,Tyrol (Tirol),2000.0,101.0,61.0,17.0,55,European Euro,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","4,0","5,0","5,0","5,0","5,0","5,0",AT,47.516231,14.550072,179
1,http://www.skiresort.info/ski-resort/ischglsam...,4.8,Ischgl/Samnaun – Silvretta Arena,5.0,15.0,Europe,Austria,Tyrol (Tirol),2872.0,47.0,142.0,49.0,53,European Euro,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","5,0","5,0","4,0","4,0","5,0","4,0",AT,47.516231,14.550072,238
2,http://www.skiresort.info/ski-resort/skiwelt-w...,4.8,SkiWelt Wilder Kaiser-Brixental,5.0,26.0,Europe,Austria,Tyrol (Tirol),1957.0,122.0,129.0,33.0,49,European Euro,"5,0",5.0,"5,0",4.0,"5,0","4,0","5,0","5,0","5,0","4,0","4,0","5,0","5,0","5,0","5,0",AT,47.516231,14.550072,284
3,http://www.skiresort.info/ski-resort/st-antons...,4.8,Ski Arlberg,5.0,200.0,Europe,Austria,Tyrol (Tirol),2811.0,132.0,123.0,50.0,53,European Euro,"5,0",5.0,"5,0",5.0,"4,0","4,0","4,0","4,0","5,0","5,0","5,0","5,0","5,0","4,0","4,0",AT,47.516231,14.550072,305
4,http://www.skiresort.info/ski-resort/serfaus-f...,4.8,Serfaus-Fiss-Ladis,5.0,28.0,Europe,Austria,Tyrol (Tirol),2820.0,47.0,123.0,28.0,51,European Euro,"5,0",5.0,"5,0",5.0,"4,0","5,0","4,0","4,0","5,0","4,0","4,0","5,0","4,0","5,0","4,0",AT,47.516231,14.550072,198

#### Antes de transformar las variables, comprobamos el tipo de dato para identificar aquellas que han sido importadas como texto y necesitan convertirse a formato numérico.

In [18]:
df[columnas_revision].dtypes

Stars                                                         float64
Rate                                                          float64
Ski resort size                                                   str
Slope offering, variety of runs                               float64
Lifts and cable cars                                              str
Snow reliability                                              float64
Access, on-site parking                                           str
Orientation (trail map, information boards, sign-postings)        str
Cleanliness and hygiene                                           str
Environmentally friendly ski operation                            str
Mountain restaurants, ski huts, gastronomy                        str
Après-ski                                                         str
Accommodation offering directly at the slopes and lifts           str
Beginners                                                         str
Snow parks                                                        str
Cross-country skiing and trails                                   str
Families and children                                             str
Km Freeride                                                   float64
dtype: object

In [19]:
df["Après-ski"].value_counts(dropna=False)

Après-ski
NaN    5049
3,0     174
2,0     106
4,0      75
1,0      64
5,0      10
Name: count, dtype: int64

In [20]:
df["Families and children"].value_counts(dropna=False)

Families and children
NaN    5049
4,0     179
3,0     112
5,0     108
2,0      27
1,0       3
Name: count, dtype: int64

#### Las variables de valoración se convierten a formato numérico sustituyendo la coma decimal por un punto. Esto permitirá utilizarlas posteriormente en cálculos y visualizaciones.

In [21]:
columnas_valoracion = [
    "Ski resort size",
    "Lifts and cable cars",
    "Access, on-site parking",
    "Orientation (trail map, information boards, sign-postings)",
    "Cleanliness and hygiene",
    "Environmentally friendly ski operation",
    "Mountain restaurants, ski huts, gastronomy",
    "Après-ski",
    "Accommodation offering directly at the slopes and lifts",
    "Beginners",
    "Snow parks",
    "Cross-country skiing and trails",
    "Families and children"
]

In [22]:
for columna in columnas_valoracion:
    df[columna] = (
        df[columna]
        .str.replace(",", ".", regex=False)
        .astype(float)
    )

In [23]:
df[columnas_valoracion].dtypes

Ski resort size                                               float64
Lifts and cable cars                                          float64
Access, on-site parking                                       float64
Orientation (trail map, information boards, sign-postings)    float64
Cleanliness and hygiene                                       float64
Environmentally friendly ski operation                        float64
Mountain restaurants, ski huts, gastronomy                    float64
Après-ski                                                     float64
Accommodation offering directly at the slopes and lifts       float64
Beginners                                                     float64
Snow parks                                                    float64
Cross-country skiing and trails                               float64
Families and children                                         float64
dtype: object

#### ¿Las columnas con un 92 % de nulos corresponden siempre a las mismas estaciones?

In [24]:
df[df["Après-ski"].notna()].shape

(429, 33)

In [25]:
df[df["Families and children"].notna()].shape

(429, 33)

In [26]:
df[df["Snow reliability"].notna()].shape

(429, 33)

In [30]:
df[
    [
        "NameResort",
        "Country",
        "Rate",
        "Après-ski",
        "Families and children",
        "Snow reliability"
    ]
].dropna().head(390)

,NameResort,Country,Rate,Après-ski,Families and children,Snow reliability
0,KitzSki – Kitzbühel/Kirchberg,Austria,4.9,4.0,5.0,5.0
1,Ischgl/Samnaun – Silvretta Arena,Austria,4.8,5.0,4.0,5.0
2,SkiWelt Wilder Kaiser-Brixental,Austria,4.8,4.0,5.0,4.0
3,Ski Arlberg,Austria,4.8,5.0,5.0,5.0
4,Serfaus-Fiss-Ladis,Austria,4.8,4.0,5.0,5.0
...,...,...,...,...,...,...
3585,bolton-valley,USA,3.0,2.0,3.0,4.0
3596,breckenridge,USA,4.0,4.0,5.0,5.0
3611,buttermilk-mountain,USA,3.0,2.0,4.0,4.0
3702,heavenly,USA,4.0,4.0,4.0,5.0
3736,keystone,USA,4.0,4.0,5.0,5.0

#### Analizamos las filas con valor nulo en la columna de país para tomar una decisión adecuada.

In [31]:
df[df["Country"].isna()]

,URL,Rate,NameResort,Stars,Km Freeride,Continent,Country,State/Province,Altitude,Easy,Intermediate,Difficult,Adult,Currency,Ski resort size,"Slope offering, variety of runs",Lifts and cable cars,Snow reliability,"Access, on-site parking","Orientation (trail map, information boards, sign-postings)",Cleanliness and hygiene,Environmentally friendly ski operation,"Mountain restaurants, ski huts, gastronomy",Après-ski,Accommodation offering directly at the slopes and lifts,Families and children,Beginners,Snow parks,Cross-country skiing and trails,country,latitude,longitude,Total Kms
1830,http://www.skiresort.info/ski-resort/wildhaus-...,3.9,. Wildhaus – Gamserrugg (Toggenburg),3.0,12.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1831,http://www.skiresort.info/ski-resort/ehrwalder...,3.5,. Ehrwalder Wettersteinbahnen – Ehrwald,2.0,1.5,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1832,http://www.skiresort.info/ski-resort/ravna-pla...,3.0,. Ravna Planina,2.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1833,http://www.skiresort.info/ski-resort/savin-kuk...,2.9,. Savin Kuk – Žabljak,3.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1834,http://www.skiresort.info/ski-resort/snowworld...,2.7,. SnowWorld Rucphen (indoor ski area),1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1835,http://www.skiresort.info/ski-resort/raudalen/,NaN,. Raudalen,3.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1836,http://www.skiresort.info/ski-resort/snowworld...,NaN,. SnowWorld Terneuzen (indoor ski area),1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1837,http://www.skiresort.info/ski-resort/snowworld...,NaN,. SnowWorld Amsterdam (indoor ski area),1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1838,http://www.skiresort.info/ski-resort/roelzhang...,NaN,. Rölzhang – Wildenthal,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [32]:
df[df["Total Kms"] == 0].shape

(2117, 33)

In [34]:
df[df["Total Kms"] == 0][
    ["NameResort", "Country", "Total Kms", "Easy", "Intermediate", "Difficult"]
].head(300)

,NameResort,Country,Total Kms,Easy,Intermediate,Difficult
140,. Burglift – Stans,Austria,0,0.5,0.0,0.0
143,. Hohe Wand Wiese – Vienna (High Hills),Austria,0,0.1,0.4,0.0
145,. Alfaierlift – Gschnitz,Austria,0,0.3,0.2,0.0
147,. Kramsach,Austria,0,0.4,0.0,0.0
155,annerlbauerlifte-krieglach,Austria,0,0.5,0.0,0.0
...,...,...,...,...,...,...
1382,talma,Finland,0,0.5,0.3,0.0
1384,tornimaeki-mikkeli,Finland,0,0.0,0.0,0.0
1388,vatuski,Finland,0,0.0,0.0,0.0
1389,vierumaeki,Finland,0,0.0,0.0,0.0
1392,vuorenmaa,Finland,0,0.0,0.0,0.0

#### Aquí se ve que hay muchas estaciones con 0 km esquiables

In [35]:
df[df["Total Kms"] == 0]["Easy"].value_counts(dropna=False)

Easy
0.0    935
0.3    260
0.2    215
0.5    209
0.4    179
0.1    117
0.6     79
0.8     58
0.7     46
0.9     19
Name: count, dtype: int64

In [36]:
df[df["Total Kms"] == 0]["Intermediate"].value_counts(dropna=False)

Intermediate
0.0    1876
0.2      66
0.3      51
0.1      42
0.4      35
0.5      24
0.6      10
0.8       6
0.7       5
0.9       2
Name: count, dtype: int64

In [37]:
df[df["Total Kms"] == 0]["Difficult"].value_counts(dropna=False)

Difficult
0.0    2085
0.1      17
0.2       9
0.3       4
0.4       2
Name: count, dtype: int64

In [38]:
df[df["Total Kms"] > 0].shape

(3361, 33)

#### Comprobamos la consistencia de la variable `Total Kms` comparándola con la suma de los kilómetros de pistas fáciles, intermedias y difíciles.

In [39]:
df["Total Kms Calculados"] = (
    df["Easy"] +
    df["Intermediate"] +
    df["Difficult"]
)

In [40]:
(
    df["Total Kms"] != df["Total Kms Calculados"]
).sum()

np.int64(2458)

In [41]:
df[
    ["Easy", "Intermediate", "Difficult", "Total Kms", "Total Kms Calculados"]
].head(20)

     Easy  Intermediate  Difficult  Total Kms  Total Kms Calculados
0   101.0          61.0       17.0        179                 179.0
1    47.0         142.0       49.0        238                 238.0
2   122.0         129.0       33.0        284                 284.0
3   132.0         123.0       50.0        305                 305.0
4    47.0         123.0       28.0        198                 198.0
5   140.0         112.0       18.0        270                 270.0
6    28.7          41.3       13.0         83                  83.0
7    43.0          89.0       11.0        143                 143.0
8    46.4          68.3        8.3        122                 123.0
9    70.2          44.6       29.4        144                 144.2
10   60.0          45.0        8.0        113                 113.0
11   40.0          63.0       33.0        136                 136.0
12   61.0          35.0        4.0        100                 100.0
13   35.0          55.0       20.0        110                 110.0
14   52.0          41.0       19.0        112                 112.0
15   30.0          81.0        4.0        115                 115.0
16   30.0          28.0       19.0         77                  77.0
17   29.0          25.0       10.0         64                  64.0
18   13.0          25.0        3.0         41                  41.0
19   30.6          52.8        2.6         86                  86.0

In [42]:
df[
    df["Total Kms"] != df["Total Kms Calculados"]
][
    ["NameResort", "Easy", "Intermediate", "Difficult", "Total Kms", "Total Kms Calculados"]
].head(20)

,NameResort,Easy,Intermediate,Difficult,Total Kms,Total Kms Calculados
8,Schladming – Planai/​Hochwurzen/​Hauser Kaibl...,46.4,68.3,8.3,122,123.0
9,Sölden,70.2,44.6,29.4,144,144.2
22,Ski Juwel Alpbachtal Wildschönau,25.9,53.7,13.5,93,93.1
23,Damüls Mellau,29.7,48.0,1.7,79,79.4
30,Großarltal/Dorfgastein,25.5,43.1,1.5,70,70.1
33,Lermoos – Grubigstein,12.8,12.6,1.9,27,27.3
34,Golm,13.0,12.0,1.5,26,26.5
42,. Sillian – Thurntaler (Hochpustertal),5.6,15.0,1.1,21,21.7
44,. Spieljoch – Fügen,3.6,14.8,2.7,21,21.1
50,. Pitztal Glacier (Pitztaler Gletscher),3.8,16.2,0.7,20,20.7
54,. Ehrwalder Alm – Ehrwald,18.1,7.4,2.0,27,27.5
58,Kaunertal Glacier (Kaunertaler Gletscher),13.0,5.1,2.7,20,20.8
63,Moelltal Glacier (Mölltaler Gletscher),5.2,7.2,5.0,17,17.4
65,Gargellen,20.8,5.3,2.0,28,28.1
67,. Rauriser Hochalmbahnen – Rauris,15.0,12.5,5.0,32,32.5
70,. Gerlitzen,10.5,27.8,3.3,41,41.6
77,. Mönichkirchen/Mariensee,5.5,6.0,2.0,13,13.5
78,Sportgastein,3.5,13.2,1.5,18,18.2
80,. Rosshütte – Seefeld,11.4,5.9,1.0,18,18.3
81,Sonnenkopf – Klösterle,12.8,15.9,0.8,29,29.5

#### Analizamos los registros en los que el total de kilómetros no coincide con la suma de pistas fáciles, intermedias y difíciles para decidir si conviene corregir la variable original. Eliminamos la columna original y nos quedamos ocn la oclumna generada.

In [43]:
# Eliminar la columna original
df.drop(columns="Total Kms", inplace=True)

# Renombrar la columna calculada
df.rename(
    columns={"Total Kms Calculados": "Total Kms"},
    inplace=True
)

In [44]:
df[["Easy", "Intermediate", "Difficult", "Total Kms"]].head()

    Easy  Intermediate  Difficult  Total Kms
0  101.0          61.0       17.0      179.0
1   47.0         142.0       49.0      238.0
2  122.0         129.0       33.0      284.0
3  132.0         123.0       50.0      305.0
4   47.0         123.0       28.0      198.0

### Limpieza de los nombres de las estaciones

In [45]:
df["NameResort"].str.startswith(".").sum()

np.int64(254)

In [46]:
df["NameResort"] = df["NameResort"].str.lstrip(". ").str.strip()

In [47]:
df["NameResort"].head(20)

0                         KitzSki – Kitzbühel/Kirchberg
1                      Ischgl/Samnaun – Silvretta Arena
2                       SkiWelt Wilder Kaiser-Brixental
3                                           Ski Arlberg
4                                    Serfaus-Fiss-Ladis
5     Saalbach Hinterglemm Leogang Fieberbrunn (Skic...
6     Kaltenbach – Hochzillertal/Hochfügen (SKi-opti...
7     Zillertal Arena – Zell am Ziller/Gerlos/Königs...
8     Schladming – Planai/​Hochwurzen/​Hauser Kaibli...
9                                                Sölden
10                                   Silvretta Montafon
11            Mayrhofen – Penken/Ahorn/Rastkogel/Eggalm
12                                           Obertauern
13                          Gurgl – Obergurgl-Hochgurgl
14               Hochkönig – Maria Alm/Dienten/Mühlbach
15    Snow Space Salzburg – Flachau/Wagrain/St. Joha...
16                          Schmittenhöhe – Zell am See
17                      Wildkogel – Neukirchen/Bramberg
18                     Kitzsteinhorn/Maiskogel – Kaprun
19    Bad Gastein/Bad Hofgastein – Schlossalm/Angert...
Name: NameResort, dtype: str

### Revisión de las divisas

In [48]:
df["Currency"].value_counts(dropna=False)

Currency
-                          1952
European Euro              1473
US Dollar                   435
Japanese Yen                316
Swiss Franc                 284
Czech koruna                231
Canadian Dollar             197
Polish zloty                125
Norwegian krone             105
Swedish krona                95
UK Pound                     49
New Zealand Dollar           24
Romanian leu                 21
Chiliean Peso                16
Russian ruble                14
Argentine Peso               13
Chinese Yuan                 12
Bosnia convertible mark      11
Icelandic krona              10
Australian dollar            10
NaN                           9
Hungarian forint              9
South Korean won              8
Ukrainian hryvnia             7
Bulgarian Lev                 6
Turkish lira                  6
Danish Krone                  5
Serbian dinar                 4
Georgian Lari                 4
Croatian Kuna                 4
Lebanese pound                4
South African rand            3
Kyrgyzstani som               3
Macedonian denar              2
Kazakhstani tenge             2
Israeli new shekel            2
Iranian rial                  1
Armenian Dram                 1
Indian rupee                  1
United Arab Emerites          1
Azerbaijani manat             1
unknown                       1
Mongolian togrog              1
Name: count, dtype: int64

In [50]:
df[df["Currency"] == "-"][["NameResort", "Country", "Adult", "Currency"]].head(200)

                                    NameResort  Country Adult Currency
143      Hohe Wand Wiese – Vienna (High Hills)  Austria     0        -
145                     Alfaierlift – Gschnitz  Austria     0        -
155                 annerlbauerlifte-krieglach  Austria     0        -
159                           aschaulift-koppl  Austria     0        -
160                          astenberg-wiesing  Austria     0        -
...                                        ...      ...   ...      ...
1048                valbella-di-gallio-sisemol    Italy     0        -
1050                             valle-divedro    Italy     0        -
1052  valpelline-ollomont-heliski-grand-combin    Italy     0        -
1054                         villaggio-palumbo    Italy     0        -
1055                    weissenbach-alpinwellt    Italy     0        -

[200 rows x 4 columns]

In [51]:
df[df["Currency"] == "-"]["Country"].value_counts()

Country
Germany      331
Japan        281
Poland       129
China        121
Canada        92
            ...
Ireland        1
Egypt          1
Brazil         1
Namibia        1
Singapore      1
Name: count, Length: 83, dtype: int64

In [52]:
paises_sin_moneda = df[df["Currency"] == "-"]["Country"].unique()
paises_sin_moneda

<StringArray>
[                     'Austria',                  'Switzerland',
                        'Italy',                       'France',
                      'Finland',                        'Spain',
                     'Bulgaria',                       'Serbia',
                       'Norway',                       'Sweden',
                     'Slovakia',                      'Germany',
       'Bosnia and Herzegovina',               'Czech Republic',
                     'Slovenia',                   'Montenegro',
                       'Poland',              'Southern Russia',
                'Liechtenstein',                      'Ukraine',
               'North Caucasus',                  'Netherlands',
                       'Greece',                      'Iceland',
                      'Romania',               'United Kingdom',
             'Northwest Russia',                    'Macedonia',
                    'Lithuania',                      'Belgium',
                      'Denmark',                          'USA',
                         'Iran',                       'Turkey',
                        'Japan',                       'Russia',
                       'Canada',       'Volga Federal District',
                        'China',        'Ural Federal District',
                 'Turkmenistan',                   'Kazakhstan',
                   'Kyrgyzstan',                     'Armenia ',
                  'South Korea',                  'New Zealand',
                    'Greenland',                        'Chile',
                        'India',                      'Morocco',
                      'Siberia',                       'Latvia',
                      'Georgia',                      'Hungary',
                    'Argentina',         'United Arab Emirates',
                      'Croatia',                    'Australia',
                      'Albania',                       'Mexico',
                   'Uzbekistan',                      'Algeria',
                         'Iraq',                        'Qatar',
                      'Lebanon',                     'Malaysia',
 'Far Eastern Federal District',                        'Nepal',
                         'Peru',                  'North Korea',
                      'Estonia',                     'Thailand',
                      'Belarus',                     'Pakistan',
                 'South Africa',               'Central Russia',
                   'Azerbaijan',                      'Bahrain',
                      'Ireland',                        'Egypt',
                       'Brazil',                      'Namibia',
                    'Singapore']
Length: 83, dtype: str

In [53]:
df[
    (df["Country"].isin(paises_sin_moneda)) &
    (df["Currency"] != "-")
].groupby("Country")["Currency"].unique()

Country
Argentina                      [Argentine Peso]
Armenia                         [Armenian Dram]
Australia                   [Australian dollar]
Austria                         [European Euro]
Azerbaijan                  [Azerbaijani manat]
                                  ...
USA                                 [US Dollar]
Ukraine                     [Ukrainian hryvnia]
United Arab Emirates     [United Arab Emerites]
United Kingdom                       [UK Pound]
Ural Federal District           [Russian ruble]
Name: Currency, Length: 61, dtype: object

In [54]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5478 entries, 0 to 5477
Data columns (total 33 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   URL                                                         5478 non-null   str
 1   Rate                                                        3471 non-null   float64
 2   NameResort                                                  5478 non-null   str
 3   Stars                                                       413 non-null    float64
 4   Km Freeride                                                 480 non-null    float64
 5   Continent                                                   5469 non-null   str
 6   Country                                                     5469 non-null   str
 7   State/Province                                              5469 non-null   str
 8   Altitude                                                    5469 non-null   float64
 9   Easy                                                        5478 non-null   float64
 10  Intermediate                                                5478 non-null   float64
 11  Difficult                                                   5478 non-null   float64
 12  Adult                                                       5469 non-null   str
 13  Currency                                                    5469 non-null   str
 14  Ski resort size                                             3452 non-null   float64
 15  Slope offering, variety of runs                             3452 non-null   float64
 16  Lifts and cable cars                                        3452 non-null   float64
 17  Snow reliability                                            429 non-null    float64
 18  Access, on-site parking                                     429 non-null    float64
 19  Orientation (trail map, information boards, sign-postings)  429 non-null    float64
 20  Cleanliness and hygiene                                     429 non-null    float64
 21  Environmentally friendly ski operation                      429 non-null    float64
 22  Mountain restaurants, ski huts, gastronomy                  429 non-null    float64
 23  Après-ski                                                   429 non-null    float64
 24  Accommodation offering directly at the slopes and lifts     429 non-null    float64
 25  Families and children                                       429 non-null    float64
 26  Beginners                                                   429 non-null    float64
 27  Snow parks                                                  429 non-null    float64
 28  Cross-country skiing and trails                             429 non-null    float64
 29  country                                                     4879 non-null   str
 30  latitude                                                    4880 non-null   float64
 31  longitude                                                   4880 non-null   float64
 32  Total Kms                                                   5478 non-null   float64
dtypes: float64(25), str(8)
memory usage: 1.4 MB

In [55]:
moneda_por_pais = (
    df[
        (df["Currency"] != "-") &
        (df["Currency"].notna())
    ]
    .groupby("Country")["Currency"]
    .first()
    .to_dict()
)

In [56]:
df.loc[df["Currency"] == "-", "Currency"] = (
    df.loc[df["Currency"] == "-", "Country"].map(moneda_por_pais)
)

In [57]:
df["Currency"].isnull().sum()

np.int64(71)

In [58]:
df[df["Currency"].isna()][["NameResort", "Country", "Adult", "Currency"]].head(30)

,NameResort,Country,Adult,Currency
1830,Wildhaus – Gamserrugg (Toggenburg),NaN,NaN,NaN
1831,Ehrwalder Wettersteinbahnen – Ehrwald,NaN,NaN,NaN
1832,Ravna Planina,NaN,NaN,NaN
1833,Savin Kuk – Žabljak,NaN,NaN,NaN
1834,SnowWorld Rucphen (indoor ski area),NaN,NaN,NaN
1835,Raudalen,NaN,NaN,NaN
1836,SnowWorld Terneuzen (indoor ski area),NaN,NaN,NaN
1837,SnowWorld Amsterdam (indoor ski area),NaN,NaN,NaN
1838,Rölzhang – Wildenthal,NaN,NaN,NaN
5017,abzakovo,Volga Federal District,0,NaN
5018,khakaborazi-planned,Volga Federal District,0,NaN
5019,kush-tau,Volga Federal District,0,NaN
5020,magnitogorsk,Volga Federal District,0,NaN
5021,mratkino-beloretsk,Volga Federal District,0,NaN
5022,ski-komplex-sok-krasnaya-glinka,Volga Federal District,0,NaN
5165,ahal-ashgabat,Turkmenistan,0,NaN
5166,balkanabat,Turkmenistan,0,NaN
5167,dashoguz,Turkmenistan,0,NaN
5168,mary,Turkmenistan,0,NaN
5169,tuerkmenabat,Turkmenistan,0,NaN
5311,azrou,Morocco,0,NaN
5312,djebel-bou-iblane,Morocco,0,NaN
5313,hoher-atlas,Morocco,0,NaN
5314,jbel-hebri,Morocco,0,NaN
5315,michlifen,Morocco,0,NaN
5316,oukaimeden,Morocco,0,NaN
5317,rif-gebirge,Morocco,0,NaN
5407,bigell-dardhe,Albania,0,NaN
5408,puke,Albania,0,NaN
5409,bosques-de-monterreal-san-antonio-de-las-alazanas,Mexico,0,NaN

In [59]:
df[df["Currency"].isna()]["Country"].value_counts(dropna=False)

Country
Central Russia            11
NaN                        9
Morocco                    7
Volga Federal District     6
Turkmenistan               5
Uzbekistan                 4
Belarus                    4
Malaysia                   3
North Korea                3
Pakistan                   3
Albania                    2
Iraq                       2
Qatar                      2
Mexico                     1
Algeria                    1
Nepal                      1
Peru                       1
Thailand                   1
Bahrain                    1
Ireland                    1
Egypt                      1
Namibia                    1
Singapore                  1
Name: count, dtype: int64

In [60]:
monedas_manuales = {
    "Morocco": "Moroccan Dirham",
    "Central Russia": "Russian ruble",
    "Volga Federal District": "Russian ruble",
    "Turkmenistan": "Turkmenistani Manat",
    "Uzbekistan": "Uzbekistani Som",
    "Belarus": "Belarusian Ruble",
    "Malaysia": "Malaysian Ringgit",
    "North Korea": "North Korean Won",
    "Pakistan": "Pakistani Rupee",
    "Albania": "Albanian Lek",
    "Iraq": "Iraqi Dinar",
    "Qatar": "Qatari Riyal",
    "Mexico": "Mexican Peso",
    "Algeria": "Algerian Dinar",
    "Nepal": "Nepalese Rupee",
    "Peru": "Peruvian Sol",
    "Thailand": "Thai Baht",
    "Bahrain": "Bahraini Dinar",
    "Ireland": "European Euro",
    "Egypt": "Egyptian Pound",
    "Namibia": "Namibian Dollar",
    "Singapore": "Singapore Dollar"
}

In [61]:
mask = df["Currency"].isna()

df.loc[mask, "Currency"] = (
    df.loc[mask, "Country"].map(monedas_manuales)
)

In [62]:
df[df["Currency"].isna()]["Country"].value_counts(dropna=False)

Country
NaN    9
Name: count, dtype: int64

In [63]:
df[df["Country"].isna()]

,URL,Rate,NameResort,Stars,Km Freeride,Continent,Country,State/Province,Altitude,Easy,Intermediate,Difficult,Adult,Currency,Ski resort size,"Slope offering, variety of runs",Lifts and cable cars,Snow reliability,"Access, on-site parking","Orientation (trail map, information boards, sign-postings)",Cleanliness and hygiene,Environmentally friendly ski operation,"Mountain restaurants, ski huts, gastronomy",Après-ski,Accommodation offering directly at the slopes and lifts,Families and children,Beginners,Snow parks,Cross-country skiing and trails,country,latitude,longitude,Total Kms
1830,http://www.skiresort.info/ski-resort/wildhaus-...,3.9,Wildhaus – Gamserrugg (Toggenburg),3.0,12.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1831,http://www.skiresort.info/ski-resort/ehrwalder...,3.5,Ehrwalder Wettersteinbahnen – Ehrwald,2.0,1.5,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1832,http://www.skiresort.info/ski-resort/ravna-pla...,3.0,Ravna Planina,2.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1833,http://www.skiresort.info/ski-resort/savin-kuk...,2.9,Savin Kuk – Žabljak,3.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1834,http://www.skiresort.info/ski-resort/snowworld...,2.7,SnowWorld Rucphen (indoor ski area),1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1835,http://www.skiresort.info/ski-resort/raudalen/,NaN,Raudalen,3.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1836,http://www.skiresort.info/ski-resort/snowworld...,NaN,SnowWorld Terneuzen (indoor ski area),1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1837,http://www.skiresort.info/ski-resort/snowworld...,NaN,SnowWorld Amsterdam (indoor ski area),1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1838,http://www.skiresort.info/ski-resort/roelzhang...,NaN,Rölzhang – Wildenthal,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

#### Eliminamos estas 9 filas con muchos valos Nan o 0 y que por tanto no tenemos infromación como para poder incluirlas.

In [64]:
df = df[df["Country"].notna()].copy()

In [65]:
df["Country"].isna().sum()

np.int64(0)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
Index: 5469 entries, 0 to 5477
Data columns (total 33 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   URL                                                         5469 non-null   str
 1   Rate                                                        3466 non-null   float64
 2   NameResort                                                  5469 non-null   str
 3   Stars                                                       404 non-null    float64
 4   Km Freeride                                                 471 non-null    float64
 5   Continent                                                   5469 non-null   str
 6   Country                                                     5469 non-null   str
 7   State/Province                                              5469 non-null   str
 8   Altitude                                                    5469 non-null   float64
 9   Easy                                                        5469 non-null   float64
 10  Intermediate                                                5469 non-null   float64
 11  Difficult                                                   5469 non-null   float64
 12  Adult                                                       5469 non-null   str
 13  Currency                                                    5469 non-null   str
 14  Ski resort size                                             3452 non-null   float64
 15  Slope offering, variety of runs                             3452 non-null   float64
 16  Lifts and cable cars                                        3452 non-null   float64
 17  Snow reliability                                            429 non-null    float64
 18  Access, on-site parking                                     429 non-null    float64
 19  Orientation (trail map, information boards, sign-postings)  429 non-null    float64
 20  Cleanliness and hygiene                                     429 non-null    float64
 21  Environmentally friendly ski operation                      429 non-null    float64
 22  Mountain restaurants, ski huts, gastronomy                  429 non-null    float64
 23  Après-ski                                                   429 non-null    float64
 24  Accommodation offering directly at the slopes and lifts     429 non-null    float64
 25  Families and children                                       429 non-null    float64
 26  Beginners                                                   429 non-null    float64
 27  Snow parks                                                  429 non-null    float64
 28  Cross-country skiing and trails                             429 non-null    float64
 29  country                                                     4879 non-null   str
 30  latitude                                                    4880 non-null   float64
 31  longitude                                                   4880 non-null   float64
 32  Total Kms                                                   5469 non-null   float64
dtypes: float64(25), str(8)
memory usage: 1.4 MB

In [68]:
df["Adult"].head(20)

0        55
1        53
2        49
3        53
4        51
5        53
6     52,50
7        52
8     51,50
9        53
10    52,50
11       52
12    45,50
13       52
14    51,50
15    51,50
16       51
17       45
18       51
19       52
Name: Adult, dtype: str

In [69]:
df["Adult"].value_counts().head(20)

Adult
0     1952
15      95
20      93
18      79
25      72
35      70
10      70
30      69
12      66
22      62
16      58
14      53
45      47
19      47
28      44
17      44
40      43
32      43
39      42
13      40
Name: count, dtype: int64

In [73]:
df[df["Adult"] == "0"][
    ["NameResort", "Country", "Currency", "Adult", "Total Kms"]
].head(10)

,NameResort,Country,Currency,Adult,Total Kms
143,Hohe Wand Wiese – Vienna (High Hills),Austria,European Euro,0,0.5
145,Alfaierlift – Gschnitz,Austria,European Euro,0,0.5
155,annerlbauerlifte-krieglach,Austria,European Euro,0,0.5
159,aschaulift-koppl,Austria,European Euro,0,0.5
160,astenberg-wiesing,Austria,European Euro,0,1.0
161,astenlift-st-veit-im-pongau,Austria,European Euro,0,0.7
162,bachrain-golling-an-der-salzach,Austria,European Euro,0,0.5
165,baldramsdorf,Austria,European Euro,0,0.5
166,bameshub-neukirchen-am-waldeeschenau,Austria,European Euro,0,0.6
168,berger-anger-berg-im-drautal,Austria,European Euro,0,0.2

In [71]:
df[df["Adult"] == "0"]["Currency"].value_counts(dropna=False)

Currency
European Euro              603
Japanese Yen               281
Polish zloty               129
Chinese Yuan               121
Canadian Dollar             92
US Dollar                   87
Russian ruble               79
Romanian leu                72
Czech koruna                70
Swiss Franc                 52
Ukrainian hryvnia           41
UK Pound                    31
Turkish lira                30
Swedish krona               23
Serbian dinar               21
Indian rupee                21
Iranian rial                20
Kyrgyzstani som             18
New Zealand Dollar          16
Bulgarian Lev               14
Danish Krone                14
South Korean won            13
Norwegian krone              7
Moroccan Dirham              7
Macedonian denar             6
Argentine Peso               6
Croatian Kuna                6
Bosnia convertible mark      5
Turkmenistani Manat          5
Hungarian forint             5
United Arab Emerites         5
Australian dollar            5
Uzbekistani Som              4
Belarusian Ruble             4
Kazakhstani tenge            3
Lebanese pound               3
Malaysian Ringgit            3
North Korean Won             3
Pakistani Rupee              3
Armenian Dram                2
Georgian Lari                2
Albanian Lek                 2
Iraqi Dinar                  2
Qatari Riyal                 2
Icelandic krona              1
Chiliean Peso                1
Mexican Peso                 1
Algerian Dinar               1
Nepalese Rupee               1
Peruvian Sol                 1
Thai Baht                    1
South African rand           1
Azerbaijani manat            1
Bahraini Dinar               1
Egyptian Pound               1
unknown                      1
Namibian Dollar              1
Singapore Dollar             1
Name: count, dtype: int64

#### Convertimos en numérico la columna del precio del forfait

In [74]:
df["Adult"] = pd.to_numeric(df["Adult"], errors="coerce")

### Clasificación tamaño de las estaciones

#### Se crea una nueva columna que clasifica las estaciones según el total de kilómetros esquiables. Esta categorización facilitará la segmentación de los destinos y permitirá realizar comparaciones más representativas en el análisis.

In [75]:
def clasificar_tamano(km):
    if km < 5:
        return "Muy pequeña"
    elif km < 25:
        return "Pequeña"
    elif km < 75:
        return "Mediana"
    elif km < 150:
        return "Grande"
    else:
        return "Muy grande"

df["Tamaño estación"] = df["Total Kms"].apply(clasificar_tamano)

In [76]:
df["Tamaño estación"].value_counts()

Tamaño estación
Muy pequeña    3593
Pequeña        1291
Mediana         423
Grande          121
Muy grande       41
Name: count, dtype: int64

In [77]:
df[["NameResort", "Total Kms", "Tamaño estación"]].head(20)

,NameResort,Total Kms,Tamaño estación
0,KitzSki – Kitzbühel/Kirchberg,179.0,Muy grande
1,Ischgl/Samnaun – Silvretta Arena,238.0,Muy grande
2,SkiWelt Wilder Kaiser-Brixental,284.0,Muy grande
3,Ski Arlberg,305.0,Muy grande
4,Serfaus-Fiss-Ladis,198.0,Muy grande
5,Saalbach Hinterglemm Leogang Fieberbrunn (Skic...,270.0,Muy grande
6,Kaltenbach – Hochzillertal/Hochfügen (SKi-opti...,83.0,Grande
7,Zillertal Arena – Zell am Ziller/Gerlos/Königs...,143.0,Grande
8,Schladming – Planai/​Hochwurzen/​Hauser Kaibli...,123.0,Grande
9,Sölden,144.2,Grande
10,Silvretta Montafon,113.0,Grande
11,Mayrhofen – Penken/Ahorn/Rastkogel/Eggalm,136.0,Grande
12,Obertauern,100.0,Grande
13,Gurgl – Obergurgl-Hochgurgl,110.0,Grande
14,Hochkönig – Maria Alm/Dienten/Mühlbach,112.0,Grande
15,Snow Space Salzburg – Flachau/Wagrain/St. Joha...,115.0,Grande
16,Schmittenhöhe – Zell am See,77.0,Grande
17,Wildkogel – Neukirchen/Bramberg,64.0,Mediana
18,Kitzsteinhorn/Maiskogel – Kaprun,41.0,Mediana
19,Bad Gastein/Bad Hofgastein – Schlossalm/Angert...,86.0,Grande